### ISSUE TITLE
iOS NO_GPGS

### ISSUE THREAD

**Issue by PetrKarbula** [playgameservices/play-games-plugin-for-unity#1004]
Hey, just a small issue. When NO_GPGS is defined for iOS platform:

GPGSExportPackageUI.cs and UnsupportedAppStateClient.cs both are missing #ifdefs for NO_GPGS, thus giving buid errors.

**Comment by claywilkinson** [comment]
Thanks for the feedback!  These files have been removed from the recent versions of the plugin.  Which version are you using?  If you don't mind sharing why that version and not a newer version.  I am interested in understanding more how the plugin is adopted, used, upgraded, etc.

GPGSExportPackageUI.cs is an unused menu item for exporting the plugin and can be deleted.

UnsupportedAppStateClient.cs was a placeholder for platforms that do not support App State API.  Since AppState is fully deprecated, this file was removed.

**Comment by PetrKarbula** [comment]
HI, thanks for the info. 
I just updated today from 0.9.26 to the latest 0.9.31a. I was using even older version 0.9.21 (copy-pasted from older project). I am kinda "if it works, don't mess with it" type of person :smile: hence the no update policy.
Anyways updates were made by importing unitypackage over the old ones (didn't remove the plugin before importing). I am guessing thats why the obsolete files remained.

**Comment by claywilkinson** [comment]
Thanks - I totally respect that approach :+1:  I'll make a note of that and try to make it better.

**Comment by claywilkinson** [comment]
Added cleaning up the unused files from the previous version.
