### ISSUE TITLE
Easy way to get rid of Nearby script connection? 

### ISSUE THREAD

**Issue by pearacidic** [playgameservices/play-games-plugin-for-unity#1015]
When I publish, even though I am not using Nearby, it puts a location pull in the permissions (which I don't want). 

I have no intention of using nearby in my game, and I even tried manually editing the manifest(s) to no avail. 

Any help in rectifying this matter would be greatly appreciated. I basically want to comment out or break reference so there is no more Nearby links.

**Comment by claywilkinson** [comment]
which line are you referring to? The only permissions I see being added to AndroidManifest.xml are:

- `android.permission.ACCESS_NETWORK_STATE`                    
- `android.permission.INTERNET`
- `android.permission.WRITE_EXTERNAL_STORAGE`

And if you are using Google Plus to get account information:

- `android.permission.GET_ACCOUNTS`      
- `android.permission.USE_CREDENTIALS`

are added.

**Comment by pearacidic** [comment]
It is showing in GoogleDependencyGoogle.GPGS.xml

   - -<dependency>
   - <groupId>com.google.android.gms</groupId>
   - <artifactId>play-services-nearby</artifactId>
   - <version>8.1+</version>
   - </dependency>

likely due to

   - <meta-data
   android:name="com.google.android.gms.nearby.connection.SERVICE_ID"
   android:value=""/>

showing up in the AndroidManifest.xml

On Wed, Mar 2, 2016 at 12:07 PM, Clayton Wilkinson <notifications@github.com
> wrote:

> which line are you referring to? The only permissions I see being added to
> AndroidManifest.xml are:
>
>    - android.permission.ACCESS_NETWORK_STATE
>    - android.permission.INTERNET
>    - android.permission.WRITE_EXTERNAL_STORAGE
>
> And if you are using Google Plus to get account information:
>
>    - android.permission.GET_ACCOUNTS
>    - android.permission.USE_CREDENTIALS
>
> are added.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/1015#issuecomment-191327968>
> .
>



-- 
Bryan Taylor
Chess Coach
President of Kids R King, Inc.
http://www.tampabaychess.com

**Comment by claywilkinson** [comment]
Ohh - OK so there are no permissions being added for that.  This is needed because the C++ SDK that this plugin uses for Play Game Services exposes the Nearby Connection API.  There is not currently a way to remove it (The effect is that the Native Games SDK will not initialize correctly and you will not be able to authenticate).

You can experiment with removing it if you want.  The dependency is declared in https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Editor/GPGSDependencies.cs#L51

Just comment out those lines and re-run setup.
