### ISSUE TITLE
Problems building for Android platform

### ISSUE THREAD

**Issue by 11Sheep** [playgameservices/play-games-plugin-for-unity#1042]
Hi All,

I'm trying to build the Android APK (using unity cloud build) and i get this error:

Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs(21,18): error CS0234: The type or namespace name `JarResolver' does not exist in the namespace `Google'. Are you missing an assembly reference?

I'm using the latest version of the plugin (0.9.32) with the latest Unity (5.3.3) 
I'm also using google analytic plugin.

Any idea what am i missing?

**Comment by claywilkinson** [comment]
You might try exiting and restarting Unity.  The JarResolver class is in a DLL and sometimes Unity cannot load them correctly when first importing the plugin.

Next, check if you have other errors in the console related to duplicate files?

**Comment by 11Sheep** [comment]
Hi Clayton,

Thanks for the response.

I am using Unity Cloud Build, so i don't have much control on what is going on their system.
It's true, when i build it from my local computer, don't know exactly how, but i use few "voodo" tricks (like closing and opening unity, etc...) and it's working, but my goal is to use the Cloud build.

**Comment by claywilkinson** [comment]
I have to admit I have not tried the cloud build feature.  I imagine that the process is you set up your project like you want it, then save it and then it is built in the cloud?

Can you check that all the files are committed to your repository?  The class in question is in Assets/PlayServicesResolver/Editor/JarResolverLib.dll

I'd suggest filing an issue with Unity as well, since you can build locally?

I'll add cloud build to the list of things for me to try out :)  Please update this thread if you discover anything else.

**Comment by 11Sheep** [comment]
Oh no...
You are right, i was missing the JarResolverLib.dll.

It seems that the source control that i'm using was ignoring 'dll' files by default.
When i fixed it it all started working (both on cloud build and locally).

Thanks for the help!

**Comment by claywilkinson** [comment]
Great! Glad to hear it.
