### ISSUE TITLE
Windows Machine exporting Xcode iOS Project

### ISSUE THREAD

**Issue by stigmawall** [playgameservices/play-games-plugin-for-unity#1076]
Hi everyone, I'm a windows user creating a project with GPS to export for Android and iOS. I know I can't create IPA files on Windows, but I believe Unity can create XCode files on Windows. 

When I export my project to Android, it runs ok. But when I run to iOS, it gives me a popup saying "TO FINISH CONFIGURING THE EXPORTED XCODE PROJECT", with a list of frameworks to add. But this warning means pretty much nothing to me, since they didn't explain what is this frameworks, or where I can get it.

Someone already export iOS projects with GPS from Windows? How?

**Comment by sorab2142** [comment]
I haven't tried exporting the iOS project from Windows because (I think) in the Post-Build script, Cocoapods gets used to add the dependencies for the xcode project. After which instead of seeing the "TO FINISH CONFIGURING..." screen, you get a screen that says "Open the .XCWORKSPACE file to continue".

**Comment by claywilkinson** [comment]
You need to open the project in Xcode (which is the developer IDE for Mac).  The frameworks listed are standard frameworks that are shipped with Xcode.  You might want to investigate some tutorials on building Xcode projects for iOS in order to come up to speed on the terms and the general flow.

Can you run Unity on a Mac?  In that case, you can install [CocoaPods](https://cocoapods.org/) which can add the frameworks to the project for you.

**Comment by Aunday** [comment]
Is there by chance a way of doing this when we don't have access to a Mac? Only have an iPod Touch, which can test the built file, but not do the building sadly.
