### ISSUE TITLE
IOS Cloud Save?

### ISSUE THREAD

**Issue by vexe** [playgameservices/play-games-plugin-for-unity#1110]
Greetings,

More a question than an issue.

So I managed to get Google cloud save system to work with Android devices. In the past, for iOS devices we've used StansAssets' iCloudManager to save to cloud. I read that GooglePlayGames features support both iOS and Android. I wonder what does GPG do when ti comes to cloud saving on iOS? Does it delegate to Apple's cloud servers just like Stans, or does it do something different? - And, does initializing the system for iOS different than Android? (all the Builder and EnableSavedGame stuff)

I'm just worried that Apple won't accept our game if we used GPG cloud save cause we didn't use 'their' way of doing it...

Thanks.

**Comment by claywilkinson** [comment]
Google Play Game Services saves the game data to the same location as the Android implementation.  This allows games saved on an Android device to be read by the same app running on iOS.

I am not aware of anyone ever being not accepted because they used GPGS to save games, so I think it is pretty safe bet you'll be OK.
