### ISSUE TITLE
`Logger' is an ambiguous reference between `UnityEngine.Logger' and `GooglePlayGames.OurUtils.Logger'

### ISSUE THREAD

**Issue by vexe** [playgameservices/play-games-plugin-for-unity#1115]
Greetings,

Reverting to 0.9.21 trying to see if it solves some of the issues we've been having with the latest build. But I'm getting the error mentioned in the title. 'Logger' is not a very good name IMHO for a generic framework like this, it should have been prefixed with 'GP' or something... Any workarounds without having to do 'using Logger = GooglePlayGames.OurUtils.Logger' in every file the error occurs at?

Thanks.

**Comment by claywilkinson** [comment]
Reverting to an older version of Unity will fix the issue too :/  Unfortunately, there is no easy way around it.  Please share an issue if you find something weird between the current version and 0.9.21.

**Comment by vexe** [comment]
The naming could easily be solved by just renaming to GPLogger. Assuming the Logger code is not used by users it should be a painless quick simple rename process.

**Comment by claywilkinson** [comment]
True.  At the time, Unity had no Logger class - so everything was fine. Now all the references to the GooglePlayGames Logger are fully qualified (which admittedly is many more characters than GP).  I am not sure what the value of changing it now is, since it would not affect older versions of the plugins.

If you feel it would be a great improvement, please feel free to submit a pull request with the change and I'd be happy to review and merge it in.
