### ISSUE TITLE
Native Android Google+ User ID different than using Unity Plugin

### ISSUE THREAD

**Issue by sdowd-topps** [playgameservices/play-games-plugin-for-unity#1277]
Hey Everyone,
I am working on a team that has an app already in production written in Native Android.  We are porting this project to Unity.  I am noticing a discrepancy between the Google+ ID's when logging in with the same account.  Is this expected behavior?  I also noticed that the ID may return differently from Android and iOS versions of the game.  We would like to log a previous user into the new Unity version of the app but are having trouble resolving the identities based on the user's ID.  Logging in to the Native version of the app provides a user ID like this:  111689895343164004386.  While Logging in to the ported version on Unity using this plugin returns an ID like this:  g06379451278278999522

I have been looking around trying to find additional information on trying to validate an existing user and resolving the identity between the two versions of the app.  They are linked to the same project on the play console with the same client ID.  They are both labeled as the same bundle ID.  And are even signed with the same keystore.  Have I missed a key detail in regards to the ID generation?  Should the ID returned be the user's actual global Google+ ID?
Any information that could be provided in the correct way to approach this would be appreciated.  
Thank in advance.

**Comment by claywilkinson** [comment]
There currently is a migration away from using the Google+ ID for games.  You can match up the IDs using the web API which will return both the old G+ ID in the originalPlayerId field and the new Game player ID in playerId field.  More information on the reasoning for the change is discussed in this blog post: http://android-developers.blogspot.com/2016/01/play-games-permissions-are-changing-in.html

**Comment by sdowd-topps** [comment]
@claywilkinson Thank you for your quick response.  Is there a preferred endpoint of the web API to hit in order to find this mapping?  I just started messing the Google Play Game Services API testing/explorer and I'm currently looking at /players/get:
https://developers.google.com/games/services/web/api/players/get

But this only returns the (what I assume is) Game Player ID.  { "kind" : "games#player", "playerId" : <some id>, "displayName" : <name>, "banner" : <url> } etc.

Thanks again.

**Comment by claywilkinson** [comment]
It is definitely confusing.  But what I understand is that on the device, you should call getServerAuthCode and pass that to your backend server.  There, exchange the authCode for the token for the web app on behalf of the player.  Then hit players/get.  If the player has an old ID, then it will be in originalId.  Like you pointed out, new Ids are prefixed with a "g" for now, so that is a reasonable hint, but I would rely on that since it could change in the future.

If you have a new player id that does not have a an original id field, would you mind sharing your REST response with  me so I can pass it along and see what's going on on the back end.

**Comment by sdowd-topps** [comment]
Sure.  I will post the response below.  Just to be clear though:  On the Native App I logged in to Google yesterday and the ID was the global ID: 111689895.... - this may be due to the way that particular client is setup <Native Java calling into potentially older methods of retrieving user data>.  Then I loaded up the Unity client, logged in via GPGS and was assigned this game ID: g06379451...  Ideally, I could query players/get and the response would contain the known global ID for that user.  We are tracking the Google ID in our identity DB for user verification.  Preferably without having to change our server code, I could perform that query on the client and pass the proper Global ID up, particularly because we have legacy users from 4+ years ago.

Request:
https://www.googleapis.com/games/v1/players/g06379451278278999522?key={YOUR_API_KEY}

Response from my query: 
Please notice the missing (hopefully expected) field "originalPlayerId"

`{
 "kind": "games#player",
 "playerId": "g06379451278278999522",
 "displayName": "steveblacktest2",
 "bannerUrlPortrait": "http://lh3.googleusercontent.com/iXNdw4kqPIpEFFF45s8f6rJUYW9J0-OxUI9VVP2dRlY06Kj99Qy0Qi0yGuq_IlGDGMqyZK5g3FlmD-GYqA",
 "bannerUrlLandscape": "http://lh3.googleusercontent.com/I2yadG1Gyqpk2rQNtW3GfJNNKjHXBuYLULmTPdvcvx6325gNhSo-B3jcpBRzBseeHKZnyf1EaG8aeHXd6yE",
 "profileSettings": {
  "kind": "games#profileSettings",
  "profileVisible": false
 },
 "experienceInfo": {
  "kind": "games#playerExperienceInfo",
  "currentExperiencePoints": "0",
  "currentLevel": {
   "kind": "games#playerLevel",
   "level": 1,
   "minExperiencePoints": "0",
   "maxExperiencePoints": "1000"
  },
  "nextLevel": {
   "kind": "games#playerLevel",
   "level": 2,
   "minExperiencePoints": "1000",
   "maxExperiencePoints": "2500"
  }
 },
 "title": "Rookie"
}
 `

**Comment by sdowd-topps** [comment]
It should be noted that I performed this query with both the Game ID (prefaced with a "g") as well as the global ID and the response was identical.

**Comment by claywilkinson** [comment]
Thanks, I've passed it along to see what is going on. I'll update the thread when I know more.

**Comment by sdowd-topps** [comment]
Thank you for your help.

**Comment by sdowd-topps** [comment]
@claywilkinson Has there been any movement on this yet?

**Comment by claywilkinson** [comment]
Here is what I found out:
If you call player.get in the REST API with an old player ID for a game that the user signed into prior to setting a gamer tag, you'll get back both the old and new player ID... so you can do mappings in that direction.

For privacy reasons, if you call player.get with a game that the player only signed into *after* setting a gamer tag, you'll get back just the new player ID. So there is no way in general to map new player ID back to the original.

Some other facts that may help you devise a plan:
* Gamer tags are globally unique, but can be changed by users.
* This primarily affects players that are iOS only since at this time, they cannot pick a gamer tag (yet), so they do not have a "new" player Id.

If you really think it is important to map the players you can ask for the Google Plus scope and use the G+ API to get the Google+ user ID.  This is effectively the "old" player ID.  However the Games API no longer requires a Google+ account to play a game, so not all users will definitely have a G+ account.  Also, there are additional consent screens needed to access the Google+ API, increasing the initial friction to play your game.

**Comment by MixMasterRickyC** [comment]
Is there any information on how to handle and confirm the token generated via GetServerAuthCode?

Any information on this would be appreciated.

**Comment by dnnyg33** [comment]
Just updated to the latest Google play services library version (10.2) and Games.Players.getPlayerId(client) still returns what has been identified as the "old" id. Querying this user in the oAuth playground https://www.googleapis.com/games/v1/players/{playerId} returns the new id however. Is there a way to get the new id on a native android application?

**Comment by claywilkinson** [comment]
There is some stateful logic happening on the backend.  The id that is returned should be stable for the same app (identified by the packageID and the SHA1, and  game AppID) for each user.  Adding non-game scopes to the authentication will cause the non-game ID to be returned.  "Old" players who played the game before "Games Lite" was rolled out (approx Q1 2016) will have "old" ids.  New players will have new IDs.

Across new games, the player will have a stable "new" id.

To check if a player has both old and new ids, you need to:
1. Configure a web app linked to your game.
2. Use the client id of the web app to request a server auth code when authenticating on the device.
3. send the server auth code to the backend web app, and exchange it for an access token.
4. verify the token by calling [games/applications/verify](https://developers.google.com/games/services/web/api/applications/verify) with the auth token. 

In the response, if the field `alternate_player_id` is populated, it will be the other ID.
