### ISSUE TITLE
Why no Javascript?

### ISSUE THREAD

**Issue by ilias1111** [playgameservices/play-games-plugin-for-unity#128]
You have done an excelent job in this plugin but why you don't support javascript? Some of us don't know c# :(

**Comment by claywilkinson** [comment]
Thanks for the request for javascript interface.  I am marking this as an enhancement. tracking internally as 19125699

**Comment by ffff1111** [comment]
I got it working with javascript perfectly.

Just change this:
Social.localUser.Authenticate (success => {  			if (success) {.....}else{...}           });
to this:
Social.localUser.Authenticate (function (success) {   	if (success) {.....}else{...}           });

This:
((PlayGamesPlatform) Social.Active).SignOut();
to this:
(Social.Active as PlayGamesPlatform).SignOut()

Yo must move the GooglePlayGames Folder to Standar Assets (or Plugins).
And in GPGSUtil.cs change GameInfoPath to:
GameInfoPath = "Assets/Standard Assets/GooglePlayGames/GameInfo.cs";

It would be better if GPGSUtil.cs finds the file automatically instead of having to modify the script everytime by javascript users.

**Comment by claywilkinson** [comment]
Sounds like all is good - OK to close this issue?

**Comment by rodolforubens** [comment]
If I try to compile the game with the GooglePlayGames folder inside the Plugins folder or Standard Assets folder I get 4 errors in the console...

**Comment by MofoMan2000** [comment]
What are the errors? What version of Unity are you using? Latest version of the plugin?

**Comment by rodolforubens** [comment]
The errors are:

Assets/Plugins/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs(20,11): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing a using directive or an assembly reference?
Assets/Plugins/GooglePlayGames/Editor/GPGSIOSSetupUI.cs(20,9): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing a using directive or an assembly reference?
Assets/Plugins/GooglePlayGames/Editor/GPGSInstructionWindow.cs(20,11): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing a using directive or an assembly reference?
Assets/Plugins/GooglePlayGames/Editor/NearbyConnectionUI.cs(20,11): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing a using directive or an assembly reference?

Unity 5.0.2f1, yes, everything up to date!

**Comment by rodolforubens** [comment]
I think that scripts inside Plugins are compiled first then the Editor ones, then the files inside the editor maybe is not finding the namespaces necessary? I put all the files that were inside Assets/GooglePlayGames/Editor inside of Assets/Editor.

It is compiling now, let's see if it will work fine...

**Comment by rodolforubens** [comment]
Yep, it worked, you guys can close it again! :+1:
