### ISSUE TITLE
No support for hiding players in leaderboard?

### ISSUE THREAD

**Issue by alternativerichie** [playgameservices/play-games-plugin-for-unity#1282]
Is there any support for the functionality to hide players from the leaderboard as per Players.hide?
I can't find how to call this within Unity.

https://developers.google.com/games/services/management/api/players/hide

Thanks

Richie

**Comment by alternativerichie** [comment]
Found this tool, but what a waste of time to setup.  

https://github.com/playgameservices/management-tools

The sample uses Bower and Polymer!  Set those up first.  Then serve the demo-utils folder from a web server!  I just want to hide a player!  On Amazon, you can just do that directly from the Developer Portal. Took me less than 2 minutes to remove all the scores of my tester, I could view scores on all leaderboards directly in the portal.

Please provide something efficient that doesn't kill productivity and I don't have to waste time figuring out how to use it.

Thanks

**Comment by claywilkinson** [comment]
This API for for game "publishers" and not intended to be used from the game itself.  That's why it is not part of the plugin.  The typical use case is the game publisher decides that some player has submitted a false score, or violated some rule/agreement/etc.  The publisher can then call hide to hide that player from the leaderboard.

Thanks for the suggestion of adding this API to the developer console - I'll pass it along.
