### ISSUE TITLE
Free version

### ISSUE THREAD

**Issue by calebebrim** [playgameservices/play-games-plugin-for-unity#1345]
I want to use this; but I'm wondering about if it works on free version of unity3d since I can't Import from native libraries. Someone give me a light?

**Comment by Leuthil** [comment]
Unity 5 has all of the Pro features even in the Free tier (Personal Edition). Which version of Unity are you using?

**Comment by calebebrim** [comment]
I'm using 5.4.0f3, it is supposed to work on this version?

**Comment by Leuthil** [comment]
Yup.

**Comment by calebebrim** [comment]
Does it means that now Free Unity accept plugins build for android or IOS for example? And about Google Play plugin... There is an example where I can follow the instructions?

**Comment by jmottershead94** [comment]
@Leuthil Hey! You said you have it working for Unity 5.4.0f3, which is the version I am using. Just wondering if you had to change anything for iOS development? PBX classes/files are not being found on mine, and I noticed the entire xcode namespace was commented out because of a compiler variable checking to see if it was Unity 5.

When I comment the compiler variable out, all the PBX classes/types are not found. Do you know where that using is? Or what you had to change for that? I can't seem to find it under using GooglePlayGames.Editor etc.

**Comment by Leuthil** [comment]
@jmottershead94 Sorry I haven't tried iOS just yet since I was waiting for my Android version to be further on in development. It will probably take me a while before I get to that so I won't be able to help you (I don't even have an iOS developer license yet).

**Comment by jmottershead94** [comment]
@Leuthil Yeah no problem, I am trying it on my Windows OS, might have to switch to my Mac OSX system in VirtualBox and test on that with XCode installed perhaps?

If so, feels like that class should have a compiler variable checking if the OS is windows or not instead of just Unity 5, or at least that's what I would think. Thanks for commenting back anyway.
