### ISSUE TITLE
Plugin is not working.

### ISSUE THREAD

**Issue by aykutuludag** [playgameservices/play-games-plugin-for-unity#1391]
I am using latest Unity version (5.4.1) and latest Android Studio & SDK versions. However this plugins does not work and prevent export as APK. You can check extra details here: http://stackoverflow.com/questions/39682311/commandinvokationfailure-unable-to-convert-classes-into-dex-format-in-unity

Until I deleted this plugin, I can't able to export apk. I deleted this plugin and now I can export as APK however this is only temporary solution. Please fix this plugin.

**Comment by kkondarev** [comment]
Check if you have duplicate older jars, was the case with me.
Otherwise it's is working fine for me with Unity 5.3 and 5.4.
Cheers.

**Comment by aykutuludag** [comment]
I check everything. I only install this plugin and I can't export, I delete this plugin and I can export. This shows that there is a problem with plugin.

**Comment by kkondarev** [comment]
Well, is not that easy, I had to check the contents and look for duplicate classes.
Otherwise checked your stackoverflow topic, looks very much like what I had... let me see if i can find at least what jar was the issue in my case...
Got it, in my case was: Unity/Framework/Assets/Plugins/Android/android-support-v4.jar
Will post it also there, in case this helps...

**Comment by claywilkinson** [comment]
Thanks for sharing how you got it working.
