### ISSUE TITLE
GetToken() prompts to 'Choose an account'

### ISSUE THREAD

**Issue by ZenithCode** [playgameservices/play-games-plugin-for-unity#1414]
Hi,

Since we updated to 0.9.34 we are getting prompted to 'choose an account' when calling 'GooglePlayGames.PlayGamesPlatform.Instance.GetToken()'.

At this point the user is already authenticated and friends loaded so we're not sure why you get to choose the account again.

Note: I have only 1 Google Account on the device.

Can anyone help us find what's wrong please?

Thanks,
Anthony

**Comment by MixMasterRickyC** [comment]
I also get the same thing but when using

`GooglePlayGames.PlayGamesPlatform.Instance.GetAccessToken()`

The problem is also made worse when you have multiple accounts, 

For example:
1. "Choose account for Google Play Games" appears
2. You choose to sign into the first account in the list.
3. Then "Choose an account" appears, 
4. Select the second account in the list.
5. You now have the access token from the first and the email from the second.

Do we have a fix or a work around? We don't want to see the "Choose an account" selection panel.

Cheers,
Rick.

**Comment by MixMasterRickyC** [comment]
You also get the issue where the id is for the first account but the access token seems to come for the second account? So our backend fails it as we don't have a match.

Unless the user specifically selects the same account both times we get conflicting data and the user is going to be confused.

**Comment by claywilkinson** [comment]
You should not use the token API - it has been deprecated.  You should use getServerAuthCode and exchange that code on your server to get the token.

**Comment by ZenithCode** [comment]
Thanks @claywilkinson
