### ISSUE TITLE
Google Plus User ID

### ISSUE THREAD

**Issue by inessa-aks** [playgameservices/play-games-plugin-for-unity#1427]
I need to check "Google Plus User ID" after authentification with Google Play Games Services using play-games-plugin-for-unity.

As I realize Google Play Games Services uses Google+ account with user credentials for authentification.

So it should be "Google Plus User ID" value that corresponds to Google+ account being authenificated.

Does play-games-plugin-for-unity provide opportunity to read Google+ user profile info and "Google Plus User ID"?

Is there any other way to read "Google Plus User ID"?

Thanks.

**Comment by Qbit86** [comment]
@inessa-aks As far as I understand (please correct me if I'm wrong), Google Play Games uses separate account — Games account. It can be (implicitly) connected with Google account in one-to-one or many-to-one relationship (I don't know all details). But the fact is: knowing player's only Games account id or username, you cannot derive his Google account (gmail, G+) — by design. You need more privileges to get access to “full” account, while Games account is not that security-sensitive.

**Comment by inessa-aks** [comment]
I found that by calling

((PlayGamesPlatform)Social.Active).GetUserId();

I can get user's Google ID.

It seems that I am getting Google account ID, connected with gmail, because value being read doesn't coincide with my Google+ ID value.

I can't check manually what is my Google account ID connected with gmail.

Can you confirm that 

((PlayGamesPlatform)Social.Active).GetUserId();

returns user's Google account ID connected with gmail?

**Comment by claywilkinson** [comment]
The Player.getUserId() does not correlate with the Google Account ID.  This is done in order to protect the identity of the player in a game, so that no consent is needed when playing a game.

In fact, players are no longer required to have a Google Plus account.
