### ISSUE TITLE
How to Dismiss a completed game

### ISSUE THREAD

**Issue by MrAgentSmith** [playgameservices/play-games-plugin-for-unity#1488]
Hi,

I am building a custom turn based game user interface, using the PlayGamesPlatform.Instance.TurnBased.GetAllMatches(TurnBasedMatch[] matches) PlayGamesPlatform.Instance.TurnBased.GetAllInvitations(Invitation[] allInvitations), which is all fine.  However, I cannot find any documentation or help regarding how a to dismiss a completed match, (i.e. deleting the match from the google servers from the user's perspective such that the match will no longer appear in the list of matches).  Note this dismiss option does appear in the standard view games interface, when calling PlayGamesPlatform.Instance.TurnBased.AcceptFromInbox(OnMatchStarted).

On Google's Developer page for Android (see https://developers.google.com/games/services/android/turnbasedMultiplayer) is mentions “Dismissing a match: Your game can let users dismiss a turn or invitation so that they do not have to see the match again. This hides the match from the dismisser's match list UI and causes the match to eventually expire. Other match participants can continue to play until the dismissed match expires after two weeks, or until the match is played to completion or canceled (whichever happens first). To other participants, the dismisser still appears as a participant in the match. Another player cannot take the dismisser's place.”

It goes on to give information about this dismiss command, see https://developers.google.com/android/reference/com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer#dismissMatch(com.google.android.gms.common.api.GoogleApiClient,%20java.lang.String) for more details.

Any help on how I can dismiss a match (i.e. is deleted from the list of matches the user sees) within the Unity plugin, would be gratefully appreciated.

Thank you.

**Comment by cjbonn** [comment]
If you are using the plugin exclusively, you are limited to what they implemented. The better question would be how to bypass this service to utilize the raw Google Play SDK. Been looking up how to do this to no avail, as there are auto-match stuff that are in the SDK but not in this unity plugin which is really f*ing me right now.

**Comment by claywilkinson** [comment]
@MrAgentSmith - you can call Finish or Cancel for the match and that will end the match and it should be removed from the list.

@cjbonn cjbonn: Can you give an example of what is not exposed via the plugin?

As far as getting to the SDK, on Android you can use JNI to make java calls.  The PlayerStats method does this vs. going through the C++ SDK.

**Comment by cjbonn** [comment]
@claywilkinson Seems like many of the WaitingRoom Listeners are not implemented and able to be customized or extended. Plus, there are two different results on the Waiting room based on hitting back via Phone vs "Quit match" button built into the Waiting Room itself. From what I can tell, I can't hook into either of those to handle leaving the queue gracefully. While it seems that clicking Quit Match handles cleanup tasks in the back, it isn't the same for when the user hits the back button (I'm not sure exact behavior, is this technically minimizing?) - but can't figure out how to just invoke Quit Match from that back button myself - since it doesn't appear there's a listener for it, or manual methods to call for doing this.

Alternatively, it doesn't seem there's a way to close the waiting room/leave queue via script, based on the methods provided from this plugin; (IE: Close and leave queue after 5 minutes of no matchup).

**Comment by claywilkinson** [comment]
Thanks for the detailed response - let me see what I can find out.

**Comment by cjbonn** [comment]
Thank you.

**Comment by cjbonn** [comment]
I have ended up completely ditching GPG as a result of this lack of integration and switched to GameSparks - which will still allow Google login (among twitter, facedbook, etc) and provides the features I was looking for originally in GPG.

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
