### ISSUE TITLE
Is this a school or TGIF project?!

### ISSUE THREAD

**Issue by kkondarev** [playgameservices/play-games-plugin-for-unity#1497]
Guys, is this a side project / TGIF / free time initiative, or is an official Google project? I mean not GPGS as such, but the Unity integration plugin.

If first - you are doing great job, keep up the good work and if possible - take a look here more often. Will be highly appreciated! Stop reading here.

If second... no words... worst support ever. Just look at the number of unanswered questions, many of them don't even have a single reply. I mean... unbelievable.

**Comment by wolfsmash** [comment]
Please just chill out a little bit. I'm 99.9% sure that Google did not assign a dedicated team to making this plugin. The team behind this was most likely a side project that is officially sponsored by Google. Google itself does not oversee this project. If you are confused on something, there are samples showing _everything_ this plugin has to offer. If you need something personally, message me and I will be more than happy to help.

Good luck,
Wolfsmash

**Comment by Naderino** [comment]
He's kind of right though. This project has not been updated in 2 months... Not that I'm advocating anything. It's just some of us really need the support. Although these issues are generally because the samples are not being followed correctly, I'm running into issues caused by this Unity Plugin's dependency on an old framework. Basically we are getting a 403 error due to the fact that this uses an embedded webview to sign in and google did a server check this month to disable webview sign in. It's just too bad that we have to delay our releases due to a critical issue, and this shouldn't take too long to fix... Ah well, we can't really do much but wait, but I think many of us are in this boat and are desperately calling for the dev team to fix this.

**Comment by kkondarev** [comment]
@wolfsmash dude, no idea why you took the time to write this, it is not helpful at all. Obviously you have no idea either, my own guesses are as good as yours. Unless you are part of the team? Are you? Guess not.
Also obviously there are cases not covered by documentation, otherwise people wouldn't waste their time writing here.
