### ISSUE TITLE
Leaderboard: Getting scores with LoadScores() differs from the ShowLeaderBoardGUI

### ISSUE THREAD

**Issue by firatercis** [playgameservices/play-games-plugin-for-unity#1504]
Hey there,
I use ILeaderboard.LoadScores() function to fetch the high scores stored in my leaderboard but the scores are not up to date? When I use  PlayGamesPlatform.Instance.ShowLeaderboardUI () function, they ARE up to date. I asked this question to stackoverflow, but could not take any satisfying answer, than I started a bounty on this.

http://stackoverflow.com/questions/40828345/unity-google-play-services-plugin-api-is-not-sync-with-show-leaderboard-ui-funct

Could anyone help me? I am stuck here for a long time!

Best regards
fercis

**Comment by claywilkinson** [comment]
Social leaderboard scores are in a quirky state.  The "standard" UI has access to Google + data which is used to build the list of scores, where the LoadScores API has an incomplete view of the data.  This is caused by some users are signed in with Games "Lite" accounts, and do not necessarily have matching G+ accounts.  It looks like from your question, that iOS may be also involved, which will only have legacy players for your game, or accounts that have signed into an Android device.

I know it doesn't help you resolve your issue, but maybe this helps give some insight on how to proceed.

**Comment by IterativeInteractive** [comment]
@claywilkinson any updates on this issue? Especially now that Google+ is dead.

It's been almost 3 years, but I'm still encountering the same issue on Android. I've changed CACHE_OR_NETWORK to NETWORK_ONLY in LeaderboardManager.cs but that didn't seem to help at all.

Would really appreciate any help in resolving this, as my game is heavily dependent on displaying a custom leaderboard. If LoadScores() is busted, I can't ship my game.
