### ISSUE TITLE
Reset permissions to get refresh token again

### ISSUE THREAD

**Issue by Ralstlin** [playgameservices/play-games-plugin-for-unity#1532]
Hi, Im building my backend server and I saw that the refresh token is only exchanged for the serverAuthCode the first time.. if i want to receive it again i have to go to my google account > security > permission and remove my app. So the next time I get a code and exchange it, it give me a new refresh token. Normally I dont wanna reset it, but what if the user had an issue or my registration process fails for some reason? The next registration try, I will not get a refresh token, and asking the user to go google accounts to disable the app and try again is a horrible option. Isn,t there a way to revoke the permissions remotely (api) or in this plugin so I can implement a full signout removing the permissions?

**Comment by claywilkinson** [comment]
Can you call getServerAuthCode on the client again, and then exchange that for a token on the server?

**Comment by Ralstlin** [comment]
Nope, once you exchange the first code, next ones will not return a refresh token, only the access token, only the first code one after the user allow your application give the refresh token.

**Comment by claywilkinson** [comment]
Hmm, I've  reproduced your case  - I'll let you know what I find out.

**Comment by Ralstlin** [comment]
I found that on server side, exchanging the code for tokens, seems to be a way to force it. Is needed to create a custom GoogleAuthorizationCodeFlow with ApprovalPrompt = force. I will test it soon and post the results.

**Comment by claywilkinson** [comment]
Here is what I found.  In order to get a new access_token/refresh_token pair, you need to force the user to re-consent since in the case of a game, the consent is displayed via the application running on the device.  
So, if the server loses the refresh token, a message (via GCM, or some response via REST) must be sent back to the application, and then re-authenticate the user.

Unfortunately, the Games SDK does not support forcing re-authentication, so it is not possible at this time.  There are changes to how authentication works for games coming soon: https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html
which will make this possible.

In the meantime, you can keep sending authcodes from your game to your server and exchange them for an access token.

More info at: https://developers.google.com/identity/sign-in/web/server-side-flow#step_6_send_the_authorization_code_to_the_server

**Comment by Ralstlin** [comment]
I did it!  Because the code is exchanged for an access_token, this means I can "act" as the user on my back-end server for my application. reading about the [api to revoke a token](https://developers.google.com/identity/protocols/OAuth2WebServer#offline): where you can read:  

> It is also possible for an application to programmatically revoke the access given to it. Programmatic revocation is important in instances where a user unsubscribes or removes an application. In other words, part of the removal process can include an API request to ensure the permissions granted to the application are removed.

So is as simple as calling **GET https://accounts.google.com/o/oauth2/revoke?token={access_token}** and done! I logged out/in on my app and it requested me to give permissions again! 

So now on my registration process, if the user doesn't exists on my DB, and the code is not exchanged with a refresh_token, I use the access_token to revoke the permissions with the API, then send back to the client a packet to popup a windows to explain he need to allow the app again, (accept or close the app) if the user accepts, it will auto logout/login to prompt the permission window, if not, close the app and the next time is opened the permission windows will popup.

Hope this helps if someone wants to do this too.

**Comment by claywilkinson** [comment]
The plugin version 0.9.37 also has been updated to accept a flag forcing the refresh when requesting a server auth code.
