### ISSUE TITLE
PlayGamesPlatform does not exist

### ISSUE THREAD

**Issue by iinot** [playgameservices/play-games-plugin-for-unity#1545]
Just trying to implement achievements and leaderboard
Keeps saying the PlayGamesPlatform does not exist. 

Already tried all suggested methods throughout the internet.

using GooglePlayGames; - check
Service>GooglePlayGames>Setup>Android Setup , Sucessful - check
updated all SDK - check
tried right clicking PlayServiceResolver>AndroidResolver>Resolve Client Jars - check
made sure I am on android platform in build settings - check

Currently on unity version 5.5.0f3.

Receiving 4 warnings not sure if it's related.

![screen shot 2017-01-06 at 1 27 16 am](https://cloud.githubusercontent.com/assets/10860605/21684194/d7958b7c-d3b0-11e6-9c49-774cb46cba19.png)

Please help!

**Comment by claywilkinson** [comment]
The warnings are unrelated.  Are you getting this when compiling (or editing) a script?

Do you have the 
`using GooglePlayGames;` statement at the top?

**Comment by iinot** [comment]
Editing and compiling dont work it says PlayGamesPlatform does not exist.

I do have using GooglePlayGames; on top

Above with check is everything i tried so far.

**Comment by iinot** [comment]
![screen shot 2017-01-06 at 7 56 40 pm](https://cloud.githubusercontent.com/assets/10860605/21712691/3ac9ff7c-d44a-11e6-8b90-7193cd2c767e.png)
![screen shot 2017-01-06 at 7 56 34 pm](https://cloud.githubusercontent.com/assets/10860605/21712692/3acc2f7c-d44a-11e6-8fbb-2f895a8eb6b3.png)

Here are more screenshots of what I am trying to get working.

**Comment by fmmagalhaes** [comment]
The same happens to me. It was working just until yesterday I think.
I changed a few unrelated stuff (I'm almost sure) and now I can't access the leaderboard, which makes me think the login wasn't successfull. 

I also get the same warnings. Should I do something about them?

**Comment by claywilkinson** [comment]
@iinot  - Can you try to re-import the unitypackage for the plugin?

**Comment by iinot** [comment]
How should I do the re-import?

Should I delete all the imported files or just write over/replace them during the import process?

**Comment by claywilkinson** [comment]
Overwrite/replace would be fine

**Comment by iinot** [comment]
Still the same problem after reimporting.

**Comment by lukicamukica** [comment]
I'n haveing the same problemo right now. How can I solve it?

**Comment by iinot** [comment]
Hey guys,

I've got it working now. The method just does not complete itself and shows in red but it actually works. Additionally for people who can't authenticate you need to link it to the google play games service in the developers console. Additionally I did my testing through alpha and it worked perfectly. The method is still red but it works.

**Comment by KruDex** [comment]
Dear All,

I have/had similar issues and I made the following observations. 

If using Monodevelop the issues (not finding it: PlayGamesPlatform does not exist) are only appearing when building in Monodevelop in Release mode. In Debug mode it finds it - has however other issues.

When building the APK, compiling with Unity's Android toolchain it runs through without any error.

I believe it might be some '#defines' missing in Monodevelop compiler configuration. I can even see the code in the grayed out in the editor between the UNITY_ANDROID defines.

I hope it helps!

I will try to use Visual Studio as editor and see if the same issues arise.

**Comment by claywilkinson** [comment]
So to confirm, you have set the target platform to Android (or iOS) in Unity?

What version of Unity are you using?  Might be worth a bug report to Unity if monodevelop is getting confused on which constants are defined.

**Comment by KruDex** [comment]
Yes, set to Android.

I am using Unity 5.5.0f3 on Windows 10. I create a new project from scratch to verify.
- Import the PlayGames asset 0.9.36 package - no problems
- Creating script in MonoDevelop (debug mode) - PlayGamesPlatform.Activate (); success!
- Switching in MonoDevelop to release mode - PlayGamesPlatform.Activate (); Does not exist in the current context.

- Building in Unity the APK (in menu build settings) - no problem apk created since here it compiles independently from all Monodevelop settings, right?

In MonoDevelop if I check on the CSharp assembly I have NO symbols defined in release mode. In debug mode I have listed below:

Still open to do the same with Visual Studio as an editor... Will try later and post it

 DEBUG;TRACE;UNITY_5_3_OR_NEWER;UNITY_5_4_OR_NEWER;UNITY_5_5_OR_NEWER;UNITY_5_5_0;UNITY_5_5;UNITY_5;ENABLE_AUDIO;ENABLE_CACHING;ENABLE_CLOTH;ENABLE_GENERICS;ENABLE_MICROPHONE;ENABLE_MULTIPLE_DISPLAYS;ENABLE_PHYSICS;ENABLE_SPRITERENDERER_FLIPPING;ENABLE_SPRITES;ENABLE_TERRAIN;ENABLE_RAKNET;ENABLE_UNET;ENABLE_LZMA;ENABLE_UNITYEVENTS;ENABLE_WEBCAM;ENABLE_WWW;ENABLE_CLOUD_SERVICES_COLLAB;ENABLE_CLOUD_SERVICES_ADS;ENABLE_CLOUD_HUB;ENABLE_CLOUD_PROJECT_ID;ENABLE_CLOUD_SERVICES_UNET;ENABLE_CLOUD_SERVICES_BUILD;ENABLE_CLOUD_LICENSE;ENABLE_EDITOR_METRICS;ENABLE_EDITOR_METRICS_CACHING;INCLUDE_DYNAMIC_GI;INCLUDE_GI;PLATFORM_SUPPORTS_MONO;INCLUDE_PUBNUB;ENABLE_PLAYMODE_TESTS_RUNNER;ENABLE_SCRIPTING_NEW_CSHARP_COMPILER;**UNITY_ANDROID**;ENABLE_SUBSTANCE;UNITY_ANDROID_API;ENABLE_EGL;ENABLE_NETWORK;ENABLE_RUNTIME_GI;ENABLE_CRUNCH_TEXTURE_COMPRESSION;ENABLE_UNITYWEBREQUEST;ENABLE_CLOUD_SERVICES;ENABLE_CLOUD_SERVICES_ANALYTICS;ENABLE_CLOUD_SERVICES_PURCHASING;ENABLE_CLOUD_SERVICES_CRASH_REPORTING;PLATFORM_SUPPORTS_ADS_ID;UNITY_CAN_SHOW_SPLASH_SCREEN;ENABLE_VIDEO;ENABLE_VR;ENABLE_UNITYADS_RUNTIME;UNITY_UNITYADS_API;ENABLE_MONO;ENABLE_PROFILER;UNITY_ASSERTIONS;UNITY_EDITOR;UNITY_EDITOR_64;UNITY_EDITOR_WIN;UNITY_TEAM_LICENSE

**Comment by claywilkinson** [comment]
Yes, Unity does its own build of the C# code, so the release mode in mono develop does not do much.  It sounds like Unity is not generating the sln project for release correctly - I'd suggest filing a bug with Unity. 

Out of curiosity, why switch monodevelop to release mode?

**Comment by KruDex** [comment]
Switching to release mode - Just due to my wrong understanding of how unity works internally. I previously thought that via compile in Monodevelop some kind of linkable object is generated, which then is used by the other part(s) of unity and therefore it would matter for performance reason - I am from the world of programming embedded systems ;-)

I think I draw the wrong conclusions since it in order to execute the program inside unity by pressing the "play" button in unity the scripts need to be compiled in MonoDevelop... But of course building the real APK is an independent build process.

**Comment by claywilkinson** [comment]
OK thanks @KruDex.  @iinot  - OK to close this issue?

**Comment by KruDex** [comment]
Thank you - good for me to close it

**Comment by fmmagalhaes** [comment]
What about the warnings? Is it ok?

**Comment by claywilkinson** [comment]
@fmmagalhaes  - the warnings are OK - they will be cleaned up in the next build of the plugin.  Alternatively, you can fix it by removing lines 90-95 in [Assets/GooglePlayGames/Editor/GPGSDependencies.cs](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Editor/GPGSDependencies.cs#L90).

Feel free to submit a pull request with the update.

**Comment by fmmagalhaes** [comment]
Alright.

When I build my APK, either by "Build and Run" or "Build" and then transfering the file to my mobile device, I can't login. I mean, I think so, because after that, I can't access my leaderboard. However, login seems to be sucessfull, after chosing one of my google play accounts. I guess it isn't. Is it an unrelated issue?

**Comment by iinot** [comment]
Everything is working fine for me now so I am happy for this to be closed unless someone else needs more help.

**Comment by claywilkinson** [comment]
Thanks & I'm glad it is working for you now.

**Comment by fmmagalhaes** [comment]
Thanks anyway...

**Comment by john79nl** [comment]
i'm having this problem ,works in debug but not in release, any idea?
