### ISSUE TITLE
CreateWithInvitedPlayers and LoadInvitable

### ISSUE THREAD

**Issue by Leuthil** [playgameservices/play-games-plugin-for-unity#1630]
Is there ever going to be a way to Create a game with a list of playerIds? And is there ever going to be a way to simply load a list of invitable players?

It seems like the required methods are available in the Play Games C++ SDK (afaik) so I don't see why it can't be done in the Unity plugin.

I would be ok with trying to add in this functionality myself but I'm not sure where to start since it seems like it would require a rebuild of the plugin.

**Comment by claywilkinson** [comment]
I am not aware of any way to send a request to another player at this time.  Invitable players were calculated using the Google+ circles for the player.  Since Google+ is no longer integrated, this list is usually empty.

Personally, I recognize this is a pretty big gap in the functionality so I will definitely share anything I figure out.

**Comment by Leuthil** [comment]
Hmm that's unfortunate, but thanks for the follow up. I guess the API calls I remember were from a while ago with the G+ circles. I had a few neat ideas I could've implemented if this was a thing but if not I will have to make due. One of the issues I had was when friends would challenge each other it was annoying having to keep reinviting to do a rematch since you'd have to go through the UI, but I think I can work around that by simply not having the players leave the room until they explicitly don't choose to rematch.
