### ISSUE TITLE
'GoogleSignIn/GIDSignIn.h' file not found, This time in Cloud Build

### ISSUE THREAD

**Issue by marcus13345** [playgameservices/play-games-plugin-for-unity#1649]
```
10360:        [xcode] /BUILD_PATH/marcus13345.<ProjectName>.<CloudConfigName>/temp.KhQ73w/
                      Libraries/Plugins/iOS/GPGSAppController.mm:20:9:
                      fatal error: 'GoogleSignIn/GIDSignIn.h' file not found
10361:        [xcode] #import <GoogleSignIn/GIDSignIn.h>
10362:        [xcode] 1 error generated.
```

I'm running in to the error described above and in a few other issues, namely #1009 . 

Where I'm working in Cloud Build, I cant directly use XCode's GUI. To get around that, I've created a [post build script](https://gist.github.com/marcus13345/06f75d346e7591b9759112cd26de9d5a) that I believe should work, however it yields no effect. It is working, as I can see values changing in the project file, but the error persists. I'm unsure if this is my wrong doing or potentially a bug with the way Cloud Build and this plugin interact.

Edit: Updated Gist to include setting compiler flags as per PR #1579 

Any insight would be appreciated!

**Comment by GabLeRoux** [comment]
I've been struggling with this for way too long too. I sometimes think I should remove google admob and google play games from my games as it's so complicated and frustrating. This was already terrible a year ago:

Here's a few related issues
* #701 GIGSignIn.h file not found. 
* #1169 GIDSignIn.h not found   
* #1459 Build Unity project in Xcode

You may have a look to the tldr section of my comment here (scroll down):
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1459#issuecomment-256520049

But according to your gist, it sounds like you're doing it right.

I personally tried `5.1.0`, `5.1.1` and `5.1.2`.
* `5.1.0` and `5.1.2`, I'm getting same error as you.
* `5.1.1` has undeclared `kGTMOAuth2ErrorTokenUnavailable` because it uses `GoogleSignIn 4.0.2` instead of `GoogleSignIn 2.4.0`

(╯°□°）╯︵ ┻━┻

**Comment by claywilkinson** [comment]
Thanks for the details - iOS and Play Games has definitely had its problems.  Unfortunately, GPGS has been deprecated for iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html

**Comment by GabLeRoux** [comment]
Oh, definitely good to know, thanks for taking the time to post here :)
