### ISSUE TITLE
Sign In crashed when update to unity 5.5.2. GS version is 10.1.0

### ISSUE THREAD

**Issue by adambud** [playgameservices/play-games-plugin-for-unity#1666]
Is it some kind of a problem with Social.localUser.Authenticate method? After updated unity version (5.3.4 -> 5.5.2 ) and open my code in old MonoDevelop editor, method call was marked as wrong library... Now I'm using VisualStudio, unity 5.5.2 and play-game-services 10.1.0. No compilation errors, no error logs, still application crushes after build on device. Logcat shows that everything ends at authentication call...Any ideas?

**Comment by arunkarnann** [comment]
Thumbs up .happened for me also . niw checking with other unity versions .

**Comment by BAMFMarius** [comment]
#1604 I found a solution here. It's not very effective but it works.

**Comment by Honikou** [comment]
This isn't a solution, you can't show leaderboard anymore with that...

**Comment by Bulbul108** [comment]
I have been using this plugin since the very beginning. They did a great job in the past and hope this will continue in the future. Version 0.9.36 has authentication problem with latest GS version. Thanks to those guys for 10.0.1 workaround. No objection to the developers of this plugin. As a developer i am quite aware that changing something into new is not as easy as it looks. Recently i changed a lot of my published games. I want to release a latest version of my apps. In that case i have two decisions.
1. I can happy with the 10.0.1 workaround and publish my apps.
2. I can have a little bit more patience and wait for you guys to fix the problem.
Can you guys inform us about next release please.

**Comment by claywilkinson** [comment]
Update should go out this week to fix this problem.

**Comment by Bulbul108** [comment]
Thanks waiting for it

**Comment by claywilkinson** [comment]
The plugin has been updated to 0.9.37.
