### ISSUE TITLE
Firebase conflict (Android)

### ISSUE THREAD

**Issue by BurningBlueFox** [playgameservices/play-games-plugin-for-unity#1686]
Hi, i just updated the plugin to the newest version, but i noticed that it has some conflicts with the firebase plugin, i used the documentation to authorize the user and retrieve the auth code so i could pass it to the firebase plugin and log in the user.

```
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().RequestEmail().RequestServerAuthCode(false).Build();
PlayGamesPlatform.InitializeInstance(config);
PlayGamesPlatform.Instance.GetServerAuthCode();
```

However as soon as i start the Firebase initialization process it gives me errors on the console log, and i can't use the database feature from the firebase plugin (just the auth features works):
![git1](https://cloud.githubusercontent.com/assets/8820360/24923885/5626094a-1ec9-11e7-8545-2a20f5562fc2.png)
![git2](https://cloud.githubusercontent.com/assets/8820360/24923893/5b2fdfb0-1ec9-11e7-803f-fae9ffc6c85f.png)
Then i created a project from scratch and just made a basic firebase database wirte code and it worked, after some time i noticed that if i just called the firebase without doing the authentification and initialization from google play games unity plugin, it wrote to the database and gave me no errors, if i sign in from google play games first then call the firebase it doesn't write to the database and gave me errors on the log.

Anyone has similiar issues? am i missing something important?

**Comment by kzyma** [comment]
This was a bit of a pain for me to get working as well. This seems to be the first version where "GetIdToken" actually works correctly. So, what I did was stopped using server auth code (and passing that to my server for a valid token) and instead used GetIdToken. Try the below...(I hope this helps!)

1) make sure wherever you are Building the google play config you have ".RequestIdToken()" added (instead of Request Server Auth Code).

2) Then pass the ID token into GetCredential.
` string id_token = PlayGamesPlatform.Instance.GetIdToken();
 Firebase.Auth.Credential credential = Firebase.Auth.GoogleAuthProvider.GetCredential(id_token,null);`

**Comment by BurningBlueFox** [comment]
Thanks for the reply, tested it and it worked,closing this issue now.
