### ISSUE TITLE
Unable to disable 'Resolution Complete' dialogue for builds.

### ISSUE THREAD

**Issue by JimmyDeemo** [playgameservices/play-games-plugin-for-unity#1738]
When performing a build in the newer plugin versions a dialogue is displayed with the message 'Resolution Complete' prior to instigating the main part of the build process.

This is incompatible with our build machine (being unable to dismiss this dialogue) and I cannot find an option to turn this off. I have tried using turning off 'Enable background resolution' but this appears to be ignored when building.

Version 0.9.96 of the plugin and Unity version 5.4.5f1. Note: At present I am unable to use the latest version of the plugin due to similar issues described in #1732 and #1604.

**Comment by JimmyDeemo** [comment]
Please advise if this should actually be an issue for https://github.com/googlesamples/unity-jar-resolver?

**Comment by claywilkinson** [comment]
I recommend updating to 0.9.38a.  It contains the fix for #1604 and #1732 (still verifying).

How are you running Unity on your build machine?  if you add the `-batchmode` to the Unity [Command line arguments](https://docs.unity3d.com/Manual/CommandLineArguments.html) the editor dialogs are not shown.

Can you share the log of when you are trying to build?

And yes,  it sounds like this is a unity-jar-resolver issue.  You could also try to use the latest resolver plugin replacing the one in the older version of this plugin.

**Comment by JimmyDeemo** [comment]
Thanks for the information about `-batchmode`.

I will investigate furthur and look at unity-jar-resolver updates.
