### ISSUE TITLE
Where could I get idToken and accessToken?

### ISSUE THREAD

**Issue by Thaina** [playgameservices/play-games-plugin-for-unity#1740]
I use this library along with firebase library

From the document it said it need these `idToken` and `accessToken` for calling

```C#
GoogleAuthProvider.GetCredential(googleIdToken, googleAccessToken);
```

Then from https://github.com/playgameservices/play-games-plugin-for-unity/issues/1153#issuecomment-219166605 I have heard that we won't have idToken anymore. Then how can we do this with firebase?

**Comment by claywilkinson** [comment]
You can get the id token: https://github.com/playgameservices/play-games-plugin-for-unity#retrieving-players-id-token

If you pass the id token to GoogleAuthProvider, you can pass in null for the access token.

Be aware however, that the id token represents the real user identity, not their gamer tag.  This means the user will have to consent when authenticating when requesting the id token.  Also, be careful not to mix up the Player ID and the userID from Firebase.  Also, the names will be different.

**Comment by Thaina** [comment]
@claywilkinson Then what the meaning of these sentence?

> soon the getIdToken() method will not work for any games login.

**Comment by claywilkinson** [comment]
Thanks for asking!  The meaning is that the id token is actually coming from Google SignIn, not Play Games Services, which is a little confusing.  PGS has the concept of a "Gamer" identity - which includes a gamer name and one of the avatar images.  The Google SignIn's ID token does not know about this gamer identity, so all the operations with the id token will result in returning the user's real identity.

Since Firebase Auth needs the id token to work, and we know that game developers want to use Firebase, we bundled the id token into this plugin as well.
