### ISSUE TITLE
Unity Crash when Google Login

### ISSUE THREAD

**Issue by huseong** [playgameservices/play-games-plugin-for-unity#1755]
Crash happens when app open - unity version check - "google Login"
This issue didn't happen when I use (unity 5.5)
`05-23 17:59:38.701 14036-14101/? A/art: art/runtime/java_vm_ext.cc:410]     from boolean com.unity3d.player.UnityPlayer.nativeRender()
05-23 17:59:38.701 14036-14101/? A/art: art/runtime/java_vm_ext.cc:410] "UnityMain" prio=5 tid=9 Runnable
05-23 17:59:38.701 14036-14101/? A/art: art/runtime/java_vm_ext.cc:410]   at com.unity3d.player.UnityPlayer.nativeRender(Native method)
05-23 17:59:38.701 14036-14101/? A/art: art/runtime/java_vm_ext.cc:410]   at com.unity3d.player.UnityPlayer.a(unavailable:-1)
05-23 17:59:38.701 14036-14101/? A/art: art/runtime/java_vm_ext.cc:410]   at com.unity3d.player.UnityPlayer$c$1.handleMessage(unavailable:-1)
05-23 17:59:38.701 14036-14101/? A/art: art/runtime/java_vm_ext.cc:410]   at com.unity3d.player.UnityPlayer$c.run(unavailable:-1)`

**Comment by claywilkinson** [comment]
There should be more to the log - this snippet is not showing anything useful.

**Comment by Calvin2274** [comment]
I have the same issue.
Full log : https://puu.sh/w7ag2/97325b702d.txt

**Comment by claywilkinson** [comment]
@Calvin2274  - your issue is that you are using an old version of the plugin with new versions of play-services.  The line:
`Exception in dalvik/system/DexClassLoader.loadClass: java.lang.IncompatibleClassChangeError: Superclass com.google.android.gms.nearby.connection.Connections$ConnectionRequestListener of com.google.android.gms.games.nearby.NativeConnectionRequestListener is an interface (declaration of 'com.google.android.gms.games.nearby.NativeConnectionRequestListener' appears in /data/user/0/com.jungleegames.eatme.io/app_.gpg.classloader/9fc5eaac3813d9502e2c301f2645e6da_nearby.jar).
`

indicates that the java files do not match the native files.  I'd suggest updating the plugin to 0.9.39.
