### ISSUE TITLE
How to get the email which is logged in google play game service

### ISSUE THREAD

**Issue by bilklyphan** [playgameservices/play-games-plugin-for-unity#181]
I want to get the email which is logged in google play game service(in case my device add more then one google account)

Please help me!
Thanks

**Comment by hex** [comment]
+1 on this

**Comment by claywilkinson** [comment]
Tracking enhancement request as 19127154

**Comment by timmy2702** [comment]
+1 on this also. Is there away yet?

**Comment by claywilkinson** [comment]
This is added to the latest version of the plugin. See the [README.md](https://devrel.git.corp.google.com/libraries/play-games/plugin-unity/#Retrieving-players-email-or-access-token) for instructions.

**Comment by JohnTube** [comment]
hey @claywilkinson please fix that link for [README.md](https://github.com/playgameservices/play-games-plugin-for-unity#retrieving-players-email-or-access-token) (instead of [README.md](https://login.corp.google.com/request?s=up.corp.google.com:443/uberproxy/u3eouYSEmZAonM/&d=https://devrel.git.corp.google.com/libraries/play-games/plugin-unity/%3Fupxsrf%3DADBfK3a05TM_v8N-FXw2:1441071939561&maxAge=1200&authLevel=2000000&keyIds=MIG,bYU#Retrieving-players-email-or-access-token))

**Comment by claywilkinson** [comment]
oops - thanks!
