### ISSUE TITLE
Setup ads line to MainLibProj\AndroidManifest.xml which causes Gradle build failure

### ISSUE THREAD

**Issue by RodGreen** [playgameservices/play-games-plugin-for-unity#1812]
The line(s) it ads is :

` <meta-data android:name="com.google.android.gms.version"
             android:value="@integer/google_play_services_version" />`

It seems this value isn't defined yet (in the order of building) and so the build fails.

Removing the line from the file fixes the build error and seems to allow a successful build.

`stderr[
xxxxxx\gradleOut\MainLibProj\build\intermediates\bundles\release\aapt\AndroidManifest.xml:31:28-65: AAPT: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').`

**Comment by msifnioti** [comment]
I have encountered the same issue, and have replicated it with the default GPGS Sample Unity files (eg SmokeTest). I can also confirm that the build continues through Gradle if the line is removed, and the APK is built.

HOWEVER, if a score is submitted to a leaderboard, and then we attempt to view the leaderboard, the native UI crashes. It looks very similar to the issue described here (https://github.com/playgameservices/play-games-plugin-for-unity/issues/1671).

If the same project is compiled with the INTERNAL Unity build system, and the offending xml line is not removed, the APK is created successfully .  The leaderboards also work correctly now, and scores can be submitted and viewed successfully.

Our test conditions:
- GPGS 0.9.39a
-  Unity 5.5.4
- Android setup correctly
- All libs resolved to v 11.0.1

Conditions: 

- tested sample app with internal build and vanilla MainLibProj\AndroidManifest.xml  --> leaderboards and achievements work perfectly
- tested test app with gradle build and vanilla manifest -> build fails with error` stderr[ xxxxxx\gradleOut\MainLibProj\build\intermediates\bundles\release\aapt\AndroidManifest.xml:31:28-65: AAPT: No resource found that matches the given name (at 'value' with value `'@integer/google_play_services_version').
- tested test app with gradle build and amended manifest --> build succeeds. leaderboards do not work (crash after viewing)

Any help is appreciated. This issue is preventing us from submitting our App for release, as we require Gradle for our build (we have multidex support).

**Comment by RodGreen** [comment]
Have you by any chance tried including 
`<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />`
In the primary manifest? i.e. Plugins/Android/AndroidManifest.xml?

From my understanding as long as that is defined somewhere it'll be merged into the final manifest on compile.

**Comment by msifnioti** [comment]
Hi Rod,

Yes that tag is also included in our primary manifest. I'm starting to think that there is something under the hood between Gradle/Internal build system.

**Comment by msifnioti** [comment]
Update: When we build with Development Build OFF in Unity, the leaderboards work correctly with the amended manifest, and no longer crash. I am not sure why this happens, but at least it will allow us to upload the APK. That was the only difference.

**Comment by jonas-johansson** [comment]
We experience this in our project as well.

**Comment by pearl90** [comment]
Anyone found an answer for this?

**Comment by jongorr** [comment]
Also having trouble with this.

**Comment by pearl90** [comment]
My solution for this is to manually delete the line of code found in plugins/Android/MainLib/androidManifest.xml and paste it in the main androidManifest found in Plugins/android.. the sdk will work fine because in the build unity gathers all androidmanifests into one, but since im using gradle somehow its not reading this part of androidmanifest found in mainlib folder

**Comment by pearl90** [comment]
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />

**Comment by jongorr** [comment]
> plugins/Android/MainLib/androidManifest.xml

What versions are you running? I don't have this folder in my assets. I'm running gpgs 0.9.42 and resolver 1.2.59.0.

**Comment by pearl90** [comment]
Yes in the new version  they removed this file im gonna test the new version and update u if i found a fix.

**Comment by pearl90** [comment]
Found the solution, if you are using the new google play plugin version 9.42, go to GooglePlayGames/plugin/android/.. /androidManifest.xml cut the meta-data: <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" /> and paste it in your main androidManifest.xml found in assets/plugins/Android/androidmanifest.xml
Keep in note whenever you go to windows/google play games/android setup , and apply the setup the google play games will re generate its androidmanifest found in googleplaygames folder and re adds the meta data so you should always check and delete it so gradle wont throw a conflict.

**Comment by jongorr** [comment]
Thanks for the investigation, @pearl90. I only have 1 android manifest, oddly—this one: GooglePlayGames/plugin/android/.. /androidManifest.xml. When I remove the 

> <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />

it builds, but this removal may or may not be responsible for google play services crashing after launching in game. The whole thing appears to be an unstable mess.

**Comment by pearl90** [comment]
Yes you should manually create an android manifest in the assets/plugins/android/ some people found this androidmanifest because they were using another sdks ex: facebook which adds its manifest file in the assets/plugins/android. i do suggest you add the line there otherwise your sdk wont function is some cases.

**Comment by claywilkinson** [comment]
This is fixed in 0.9.50.  Gradle builds work now without having to modify files.
