### ISSUE TITLE
(0.9.39a) NearbyDroids crash after nearby client was created.

### ISSUE THREAD

**Issue by faizol** [playgameservices/play-games-plugin-for-unity#1824]
Hi all,
I've been trying to run NearbyDroids to no avail, with the game crashed every time I tried to execute it. I've browsed the relevant threads here and followed some of the recommendations (like modifying PluginVersion.cs to change public const string PlayServicesVersionConstraint = "11.0.2"; checking the aar files in folder Assets/Plugins/Android/ to make sure that the version is 11.0.2, etc), but still couldn't get the sample to run.

However I can run nearby connection option in QuizRacer sample without crashing the game. How should I go about it to solve this to be able to run NearbyDroids sample? 
Here is the logcat from the latest test that I did;
https://pastebin.com/BVmv7ETD

My system is as the following;
OS : Linux
Unity : 5.6.2
play-games-plugin-for-unity : 0.9.39a
Android SDK (Google Play services) : rev 42

TIA.

Cheers,
Faizol

**Comment by coen22** [comment]
When "PlayGamesPlatform.Nearby.StartAdvertising" is called the application crashes because the thread that should handle the nearby services can't be found.
As far as I can tell nothing goes wrong on the C# (Although these are just wrapper methods)
It goes wrong after internal static extern void NearbyConnections_StartAdvertising

**Comment by claywilkinson** [comment]
Unfortunately, this is a known issue in the C++ SDK and there is currently no work around.

**Comment by claywilkinson** [comment]
This is fixed in the 0.9.50 version of the plugin.
