### ISSUE TITLE
It is not activating

### ISSUE THREAD

**Issue by erkerkiii** [playgameservices/play-games-plugin-for-unity#1925]
The new version is not working(I'm using 2017) also somehow 0.9.21 is working but it is not building because of it is old version and not compatible with anything.Please help me i am trying to fix this issue for 3 days and didn't get any progress :(

**Comment by genaray** [comment]
Welcome to my world... got the same problem. After i reinstalled the new version it gave me an different error.. Why is this shit so buggy ??? 

You should logcat your game. Maybe its the same error as i got. I have the problem that it doesnt activate, because the logcat says that some libarys are missing or not registered.

**Comment by erkerkiii** [comment]
thanks dude i will try it

**Comment by genaray** [comment]
No problem. Just post the results here. I also hope that someone will answer and solve our problems fast.

**Comment by erkerkiii** [comment]
of course dude i hope too

**Comment by erkerkiii** [comment]
wow i just woke up and tried to build for logcat and it is connected but now not showing leaderboards this thing is very weird

**Comment by genaray** [comment]
Well thats strange... i still have the same problem ....

**Comment by erkerkiii** [comment]
well i think the problem is from android SDK somehow but i am still not sure

**Comment by erkerkiii** [comment]
i just released and alpha version and everything worked fine somehow this is really stupid i wasted 3 days...
