### ISSUE TITLE
ShowLeaderboard for leaderboardId with specific time scope

### ISSUE THREAD

**Issue by favoyang** [playgameservices/play-games-plugin-for-unity#194]
Currently GPGS API can only show leaderboard intent for specific leaderboardId, how about support select different timeScope also? This will be very useful for game with only weekly leaderboard supported. Example:

void ShowLeaderboardUI( string leaderboardId, GPGLeaderboardTimeScope timeScope )

**Comment by claywilkinson** [comment]
Tracking internally as 17015058

**Comment by Russel1** [comment]
How is the status with this feature?

**Comment by claywilkinson** [comment]
It is in 0.9.25

**Comment by FreezyExp** [comment]
why does the implementation use a different API from the standard Unity SocialPlatform, specifically implementing basically a copy UnityEngine.SocialPlatforms.TimeScope?

It should implement a drop in replacement for the gamecenter socialplatform provided by Unity

As there is already an enum with the required values, declaring it again will force platform dependent coding. Which in this case can be avoided.

solving it with this snippet, untill it can be fixed in a nicer way
```
public void ShowLeaderboardUI(string leaderboardId, UnityEngine.SocialPlatforms.TimeScope timeScope) {
	switch (timeScope) {
	case TimeScope.Today:
		ShowLeaderboardUI(leaderboardId, LeaderboardTimeSpan.Daily);
		break;
	case TimeScope.Week:
		ShowLeaderboardUI(leaderboardId, LeaderboardTimeSpan.Weekly);
		break;
	case TimeScope.AllTime:
		ShowLeaderboardUI(leaderboardId, LeaderboardTimeSpan.AllTime);
		break;
	default:
		break;
	}
}

public void ShowLeaderboardUI(String leaderboardId, LeaderboardTimeSpan span) {
	ShowLeaderboardUI(leaderboardId, span, null);
}
```
