### ISSUE TITLE
Google Play Games Sign-In and Leaderboard Issue

### ISSUE THREAD

**Issue by sunderam1996** [playgameservices/play-games-plugin-for-unity#1970]
Hey Guyz ! I have Unity Version 2017.1.1 and Google Play Games 0.9.41. I encountered an issue. The sign-in popup and leaderboard UI is not showing up. I have tried adding missing code to the Android Manifest also.

This is my code =

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;

public class LeaderboardController : MonoBehaviour {

	public static LeaderboardController instance;
	private const string LEADERBOARD_SCORE = "XXXXXXXXXXXXX";

	void Awake () {
		MakeInstance ();
	}

	void OnLevelWasLoaded(){
		ReportScore (GameController.instance.GetHighScore());
	}

	void Start(){
		PlayGamesClientConfiguration config = new 
			PlayGamesClientConfiguration.Builder()
			.Build();

		PlayGamesPlatform.DebugLogEnabled = true;

		PlayGamesPlatform.InitializeInstance(config);
		PlayGamesPlatform.Activate();
	}
	

	void MakeInstance () {
		if (instance != null) {
			Destroy (gameObject);
		} else {
			instance = this;
			DontDestroyOnLoad (gameObject);
		}
	}

	public void ConnectOrDisconnectOnGooglePlayGames(){
		Social.localUser.Authenticate ((bool success) => {
			if (success) {
				Debug.Log ("Login Sucess");
			} else {
				Debug.Log ("Login failed");
			}
		});
	}

	public void OpenLeaderBoardScore(){
		if (PlayGamesPlatform.Instance.localUser.authenticated) {
			PlayGamesPlatform.Instance.ShowLeaderboardUI ("XXXXXXXXXXXXX");
		}
		else {
			Debug.Log("Cannot show leaderboard: not authenticated");
		}
	}

	void ReportScore(int score){
		if (Social.localUser.authenticated) {
			Social.ReportScore (score, LEADERBOARD_SCORE, (bool success) => {

			});
		}
	}
}

How can I solve this problem ???

**Comment by SoloSebo** [comment]
Hi sunderam1996,
I have the same exact problem!!
- I had alot of other problems i had to downgrade my JDK i had to downgrade my SDK finally made the build work but now this! :(

**Comment by sunderam1996** [comment]
Hello SoloSebi, 
So, Is there any problem with Plugin or our code ?
Should we wait for Plugin Update ?

**Comment by SoloSebo** [comment]
Hi Sunderam1996,
I'm not sure its our code since the code seemed to work fine last year.

i also tried this https://github.com/playgameservices/play-games-plugin-for-unity/issues/1940
without any success

**Comment by sunderam1996** [comment]
Yes, same here. The issue was not fixed by adding code to the manifest => #1940

**Comment by SoloSebo** [comment]
Good news sunderam1996!
refer to https://github.com/playgameservices/play-games-plugin-for-unity/issues/1973

But the steps I did to make it work is the following
1) I had put the activity outside of the <application> instead of inside
ie: 
<application>
.....
<activity
                android:name="com.google.games.bridge.NativeBridgeActivity"
		android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
</application>

2) as mentioned in the above poste i changed my code from Social.showleaderboard() to the following
PlayGamesPlatform.Instance.ShowLeaderboardUI("YourLeaderboardID");

After a quick test everything worked!

Testing all features and will report back.

Good luck!

**Comment by sunderam1996** [comment]
Hey ! SoloSebo,
Oh yes, it actually worked using my account 👍  
But it is not working with any different account 
And, I have no Idea that Will it work if the game is uploaded on Google Play Store !

I have one more Doubt =
Should SHA-1 certificate fingerprint (App signing certificate) be Equal to Signing-certificate fingerprint (OAuth 2.0 client ID on Console.Developer.Google) ???

**Comment by martasp** [comment]
I don't understand why dummy logging doesn't work, and also I always get authentification false.

**Comment by sunderam1996** [comment]
Hello martasp,
Just follow the exact steps from #1973

**Comment by sunderam1996** [comment]
Today I uploaded my game.

I have checked that these keys are same =
- In the keystore used with my game (SHA-1 obtained from keytool.exe)
- In Google Play Developer Console (the SHA-1 obtained from "Upload certificate")
- In the API Manager (https://console.developers.google.com - Credentials)

And, "Sign-In" is not working properly.

**Comment by RobNHood03** [comment]
The plug in works fine on a normal build except showing leader board and achievements did not work at all. Adding: 

<activity android:name="com.google.games.bridge.NativeBridgeActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />

to the AndroidManifest.xml file resolved that issue.
 When converting to a Gradle build however a unresolved conflict resulted with:

<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />

This was due to a duplicate entry in the AndroidManifest.xml file. Removing that line from the AndroidManifest.xml file that the plug in generated fixes that issue.

However, one issue still remains. If you are building with gradle AND use Progaurd in your release build. The plug in and ALL of Google's features ie Auth, Leaderboards, achievements etc etc etc will no longer work. 

What needs to be fixed and updated for this plugin is to add a user.proguard.txt file with the necessary keep lines to make sure that Proguard is NOT stripping off anything that the plug in needs to work.

**Comment by khalifagates** [comment]
> Hey ! SoloSebo,
Oh yes, it actually worked using my account 👍
But it is not working with any different account
And, I have no Idea that Will it work if the game is uploaded on Google Play Store !

I have one more Doubt =
Should SHA-1 certificate fingerprint (App signing certificate) be Equal to Signing-certificate fingerprint (OAuth 2.0 client ID on Console.Developer.Google) ???

If you are still in alpha test add the other accounts you want to test on. It will work on all account only when you publish the app.

**Comment by claywilkinson** [comment]
This has been fixed in 0.9.42
