### ISSUE TITLE
Google Play Games Sign-In Issue

### ISSUE THREAD

**Issue by sunderam1996** [playgameservices/play-games-plugin-for-unity#1977]
Today I uploaded a game.
And, I have checked that these keys are same =

- In the keystore used with my game (SHA-1 obtained from keytool.exe)
- In Google Play Developer Console (the SHA-1 obtained from "Upload certificate")
- In the API Manager (https://console.developers.google.com - Credentials)

But, "Sign-In" is not working properly from other accounts. Only Iam able to sign in with my account.
Can Anyone solve this issue ?!

**Comment by Hondune** [comment]
Do you have .EnableSavedGames() in your configuration builder? If so try removing it and see if youre able to log in. I have been banging my head against a wall for over a week now because of this. I can not log in if i have saved games enabled, everything works perfectly if i remove it. Extremely frustrating considering thats the only reason i would like to implement google play in the first place. My sha-1 keys are all correct, my linked apps and auth credentials are all correct, i have saved games enabled in the play games console, i have tester accounts properly set up, ect. I have tried everything i can find online, i have tried every version of the plugin i could get working, i have tried every version of play games jars/aars all the way back to 10.0.1. Nothing changes, ERROR_NOT_AUTHORIZED every time. Unless i remove saved games, and then it logs in just fine every time.

So, rant aside, try removing saved games and see if that works for you. Also note that the sha-1 you are supposed to use changes depending on how youre using the app. If youre uploading the app through google play using google app signing then you should be using the sha-1 google assigns your app and NOT the upload sha-1. If youre testing the app locally by side loading it onto your phone then you should be using your apps sha-1 you get from the keytool. You can view both of these in the google play console under app signing without having to use the console key tool

**Comment by sunderam1996** [comment]
Omg...Thanks Sir...you are absolutely right....
Now everything is working.
You are simply awesome.
Thank u once again 👍
