### ISSUE TITLE
Google play services causes game to crash on all Android devices

### ISSUE THREAD

**Issue by dbidwell94** [playgameservices/play-games-plugin-for-unity#2056]
Upon calling the Authenticate() method, game crashes on all android devices. using latest version of plugin and latest version of unity. Building for android devices with android 5.1+. Issue has been confirmed using my LG V20 running Android 7.1

**Comment by Thiag0VT** [comment]
I'am having the same problem, but with LG G6...

**Comment by Thiag0VT** [comment]
I solved the problem. I have created the problem deleting project.properties from GooglePlayGamesManifest.plugin where the manifest was created, because my unity was not finishied the builds, and I got the @integer manifest error. So I have commented this part

``

And now I can Authenticate without crash!

**Comment by dbidwell94** [comment]
It seems I was using Social.Authenticate() instead of PlayGamesPlatform.Authenticate(). All that work and all i needed to do was switch my class call. Oh well, Issue solved.

**Comment by MartinRouterKing64** [comment]
> It seems I was using Social.Authenticate() instead of PlayGamesPlatform.Authenticate(). All that work and all i needed to do was switch my class call. Oh well, Issue solved.

didn't work for me... :(
