### ISSUE TITLE
Callbacks not fired for match updates

### ISSUE THREAD

**Issue by geopaulm** [playgameservices/play-games-plugin-for-unity#217]
I have registered for match updates using
PlayGamesPlatform.Instance.TurnBased.RegisterMatchDelegate(OnGotMatch);

but
below function never gets triggered.
 void OnGotMatch(TurnBasedMatch match, bool shouldAutoLaunch) {
}

I get the background notification from playgames!
Any ideas?
@ToddKerpelman 
@btco 
@seandanger 
@pR0Ps 
@MofoMan2000 
@DavidSkeppstedt 
@antonlicht

**Comment by adepase** [comment]
@ToddKerpelman: I cannot get this work in a turn based gameeven in version 0.9.11, both using 
PlayGamesPlatform.Instance.TurnBased.RegisterMatchDelegate(OnGotMatch);
and
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
			.WithInvitationDelegate(OnGotInvitation)
			.WithMatchDelegate(OnGotMatch).Build();
PlayGamesPlatform.InitializeInstance(config);

as for the new documentation.
I even tried them both together (the documentation is not so clear and the sample game implements the old documentation).
I'm working on Android.
I got some callbacks, seldom and random, but I cannot understand the conditions in which they work or not. Just got them worked (seldom and random, as told before), if I received the notification AFTER the logon, never if the app was not running before or if I was logged with another user.
Is this enough to re-open the issue or have I to do something else?

**Comment by ZenithCode** [comment]
I have a similar problem with the invitation delegate.  It works much better in 0.9.11 but it still fails every now and then.

**Comment by Whyser** [comment]
Not sure if this is it all relevant or related, but what devices are you using and have you updated the Play Services on the device? For one project, I'm using another plugin and it seems the device (Nexus 10 with Android 5.0.1) experienced some serious issues with notifications not being received or got received like 5-10mins later. I factory resetted the device and updated Play Services and it seems to work now. Note however, this was with ANOTHER plugin and might not at all be the issue here. Just thought I'd give you the heads up.

**Comment by ZenithCode** [comment]
I'm testing on:
Samsung S4 - 4.4.2
Nexus 7 - 4.4.2
Samsung Tab - 4.4.4

**Comment by adepase** [comment]
I'm testing on note 3 , android 4.4.2
