### ISSUE TITLE
Are there anyway to change Google Play Service Libraries dependencies  to 15.0.+?

### ISSUE THREAD

**Issue by nostel** [playgameservices/play-games-plugin-for-unity#2203]
Hi, I'm updating to Tapdaq SDK v6.2.2 (for GDPR compliance). They're using Google Play Service Libraries v15.0.+
While this plugin is using v11.6.2
Build an empty scene, we got some duplicated method error:
```
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/api/internal/zzbr;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/api/internal/zzbs;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/api/internal/zzcd;
```

I tried to change : PluginVersion.PlayServicesVersionConstraint = "+" but not working.

Please help me!

**Comment by supersolid-Justy** [comment]
Youll need to change build.gradle file in source/SupportLib/PlayGamesPluginSupport and rebuild the project in Android Studio.

`dependencies {
    implementation 'com.google.android.gms:play-services-games:11.6+'
    implementation 'com.google.android.gms:play-services-auth:11.6+'
    implementation 'com.google.android.gms:play-services-nearby:11.6+'
}
`
to
`dependencies {
    implementation 'com.google.android.gms:play-services-games:15.0.1'
    implementation 'com.google.android.gms:play-services-auth:15.0.1'
    implementation 'com.google.android.gms:play-services-nearby:15.0.1'
}
`

**Comment by supersolid-Justy** [comment]
Sending you the recompiled .aar files, just replace your GooglePlayGames/Editor/m2repository folder with the stuff im attaching now, delete the aar files in Plugins/Android and force a play service resolve.
the new com.google.android.gms.play-services-xxx aar files should now be of version 15.0.1 in your project.

[m2repository.zip](https://github.com/playgameservices/play-games-plugin-for-unity/files/2016592/m2repository.zip)

**Comment by nostel** [comment]
Hi Justy,

It worked, thank you very much!

**Comment by defic** [comment]
I have the same issue. Should the m2repository posted by @supersolid-Justy work with no further actions? In other words do I still need to rebuild the google play games android studio project.

With the files, Unity gives the following error:

Failed to fetch the following dependencies:
com.google.games:gpgs-plugin-support:0.9.50

And also bunch of these:
Removing Assets/GooglePlayGames/Editor/m2repository/11083f74e79584f50ad394be94e2caec/asset because the asset does not exist

I have now manually fixed the the issue by disabling the resolver and copy pasting the correct 15.0.1 libraries to Plugins/Android folder, but in our workspace, the play resolver is needed for other plugins,

My setup:
Unity 5.5.5p2
Latest Firebase Analytics and Messaging (5.0)
Latest Google Play Games (0.9.50)
