### ISSUE TITLE
Why SHA1 in my keystore is different that the one in Google Play Console?

### ISSUE THREAD

**Issue by Roixo** [playgameservices/play-games-plugin-for-unity#2226]
I upload an original apk to GooglePlay Console and now i upload another apk using a keystore, but the SHA1 is different that the previous one.
Do I need to create a new app in Google Play Console?

**Comment by AssetKid** [comment]
You likely activated Google Play App Signing. Google will resign your APK file with a new certificate.

In case you need to test the application:

1. Head over to https://console.developers.google.com/apis/dashboard.
2. Select the project.
3. On the sidebar, select 'Credentials'.
4. Select the project from the Credentials tab.
5. Change the SHA-1 key and package name to whatever you want.

**DO NOT FORGET TO CHANGE THE SHA-1 KEY TO THE GOOGLE ONE ONCE YOU ARE READY TO GO LIVE.**

You can find the original SHA-1 key on your play console. 

Release Management > App Signing.

I hope this helps.

**Comment by jflavio11** [comment]
Hello, Flavio here in 2022

I have not upload any app that implements Facebook Login to Play Store since 2018 and I was having the same issue related with the _hash key_.

The _hash key_ that Facebook requires is the SHA-1 of the app converted to Base64. The _hash key_ I get of the release APK I upload to Google Play Store was not working... and that was because Google Play Console was signing again (Google App Signing feature) the APK, resulting on a different SHA-1 (and then, a different Base64 _hash key_ too).

I had to get the SHA-1 of the app from Google Play Console and convert it to Base64, then upload it to the app configuration on the Facebook Developers site.

I have not found the same issue on any other site, so I leave my experience here if that could help anyone 💯

**Comment by suchithm** [comment]
In my case .aab file created from my project is having the SHA1 code that matches with the signed Keystore SHA1 code. but after downloading it from the playstore/appcenter it is showing the different SHA1 code. because of this login by google is not working but still login by facebook works. in FB console i have not added any release hash key only debug one is there might be because of that.
now i will follow @jflavio11

**Comment by barisx** [comment]
Resetting SHA-1 (which means creating new keystore file) will work. It is important to use google services like authentication with google.
