### ISSUE TITLE
Not Working with Unity 2018.2 

### ISSUE THREAD

**Issue by Darsan1991** [playgameservices/play-games-plugin-for-unity#2319]
Not Working with Unity 2018.2 
crashing at start (sigin)

**Comment by sonipak** [comment]
Having a similar error, continues to crash after trying to sign in. My code is as follows:

`void clickedButton(){
		button.enabled = false;

		PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder ().Build ();
		PlayGamesPlatform.InitializeInstance (config);
		PlayGamesPlatform.DebugLogEnabled = true;
		PlayGamesPlatform.Activate ();

		text.text = "Signing in...";

		Social.localUser.Authenticate ((bool success) => {
			if(success)
				text.text = "Signed in successfully!";
			else
				text.text = "Sign in failed!";
		
		});
	}`

**Comment by sonipak** [comment]
I was able to get it working on the latest LTS build 2017. 4.12f1. Not sure what's causing the issue but the LTS should suffice for now.

**Comment by ppawlak** [comment]
Have a look at #2013
"It worked for me"

**Comment by MrCanan** [comment]
Hi all,

- Problem
Same as you : impossible to pass authenticate (no popup)

- Solutions
Already tested without success all solutions as #2013, etc.

- Resum
Latest commit 9e3f673 : on Feb 16
Issues : 536

I guess this repo is simply dead and Unity don't care about it, shame on they because they don't give us a real solution !

Hope someone will find a great solution for all. =)

**Comment by olehkuznetsov** [comment]
Should be fixed in 0.9.52
