### ISSUE TITLE
Player disconnects if screen turn off or app goes bacground

### ISSUE THREAD

**Issue by bbekec** [playgameservices/play-games-plugin-for-unity#2492]
Hello, 
I m working on a realtime card game.
When i test the app, players are connected each other but if one turn off screen or take application to background user disconnects. I searched on google I found that  "edit BaseGameActivity.onStop() and remove gamehelper.onStop()" but i couldnt find the classes includes these.
Any help to prevent this situation?
Thanks

**Comment by Lestat** [comment]
Its in the documentation:

> IMPORTANT: Due to the way the underlying platform works, the user's connection to the room will be severed if the user sends the game into the background. In this case, OnLeftRoom() will be called. It is not possible to reconnect to a room if this happens.

https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/RTMP.md

**Comment by bbekec** [comment]
Thanks for the reply.
I designed my game that if there is no response from the player (the game in background) in time system automatically response and the game continues. So isnt there any way to prevent the disconnection?

**Comment by kaninhot004** [comment]
So is screen turn off still disconnect or not?

**Comment by DataGreed** [comment]
I have the same issue. Player automatically disconnects when the app looses focus (user switched apps or received a system alert when the game is running).

This is very annoying.

Is there any solution in play-games-plugin-for-unity for it? 

I know it's definitely solvable in native Android SDK as mentioned here: https://stackoverflow.com/questions/44518833/real-time-multiplayer-google-play-games-services-peer-gets-disconnected-when-app

It makes sense if the user gets automatically disconnected in application forced quit or on due to extended period of inactivity, but it's very annoying then it just looses focus or phone goes to sleep.

**Comment by DataGreed** [comment]
Seems like these issues are related:
- https://github.com/playgameservices/play-games-plugin-for-unity/issues/1338
- https://github.com/playgameservices/play-games-plugin-for-unity/issues/1166

Not directly related:
- https://github.com/playgameservices/play-games-plugin-for-unity/issues/2513 - not directly, but seems like the same use-case
- https://github.com/playgameservices/play-games-plugin-for-unity/issues/1350 - same

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.

**Comment by DataGreed** [comment]
Well that's a shame
