### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by cyraid** [playgameservices/play-games-plugin-for-unity#2664]
Are there any developers here? I've been having the most problems and errors I've ever had during development just to support Google Play Game Services. Nightmare. "I made a backup go ahead" to null reference exceptions, to empty errors in the console log window.. None of this happened before I included GPG. Generating files is so error prone, could you not have just made a C# package and some extra setup instructions? Worth the extra little bit of manual edit time so I don't have to go through this nightmare experience.. Still can't build my android version. :/ Now I get a IL2CPP linker error.

**Comment by legas1** [comment]
Yes, developers are working to bring us pure java based plugin and support is a little bit limited. I'm trying to answer almost all issues in my free time as they are mostly limited to configuration. For example I successfully run this plugin on Unity 2019 1.5f1 without issues (but only for auth). Your issue is related to 2019 2.0f1 which I guess forcefully want to remove deprecated API, which was presented as these warnings:

`Assets\GooglePlayGames\Platforms\Android\Developers\JavaObjWrapper.cs(352,39): warning CS0618: 'AndroidJNI.CallByteMethod(IntPtr, IntPtr, jvalue[])' is obsolete: 'AndroidJNI.CallByteMethod is obsolete. Use AndroidJNI.CallSByteMethod method instead'`
`Assets\GooglePlayGames\Platforms\Android\Developers\JavaObjWrapper.cs(417,39): warning CS0618: 'AndroidJNI.CallStaticByteMethod(IntPtr, IntPtr, jvalue[])' is obsolete: 'AndroidJNI.CallStaticByteMethod is obsolete. Use AndroidJNI.CallStaticSByteMethod method instead'`

This issue can be probably fixed by some patch like this (I won't pull request it for now, as I didn't test it properly, but should be fine, feel free to test it):

```patch
diff --git a/Assets/GooglePlayGames/Platforms/Android/Developers/JavaObjWrapper.cs b/Assets/GooglePlayGames/Platforms/Android/Developers/JavaObjWrapper.cs
index bcc551b..147f20a 100644
--- a/Assets/GooglePlayGames/Platforms/Android/Developers/JavaObjWrapper.cs
+++ b/Assets/GooglePlayGames/Platforms/Android/Developers/JavaObjWrapper.cs
@@ -349,7 +349,11 @@ namespace Google.Developers
                 }
                 else if (t == typeof(byte))
                 {
+#if UNITY_2019_1_OR_NEWER
+                    return (T)(object)AndroidJNI.CallSByteMethod(raw, method, jArgs);
+#else
                     return (T)(object)AndroidJNI.CallByteMethod(raw, method, jArgs);
+#endif
                 }
                 else if (t == typeof(char))
                 {
@@ -414,8 +418,13 @@ namespace Google.Developers
                 }
                 else if (t == typeof(byte))
                 {
+#if UNITY_2019_1_OR_NEWER
+                    return (T)(object)AndroidJNI.CallStaticSByteMethod(
+                        rawClass, method, jArgs);
+#else
                     return (T)(object)AndroidJNI.CallStaticByteMethod(
                         rawClass, method, jArgs);
+#endif
                 }
                 else if (t == typeof(char))
                 {
```

Your other issue with IL2CPP linker error is unknown to me. So if you attach error log I may take a look on it.

**Comment by cyraid** [comment]
Thanks Legas1, I see your pull request you made there. I still get random Null Reference Exceptions associated with OnEnable() and AssetDatabase.Refresh().. This is in another issue, but I'm guessing the full Java implementation is going to fix this when it's ready?

**Comment by legas1** [comment]
Maybe yes, I hope many issues will dissapear. However you can post the errors here so I can take a look and possibly suggest fix.

**Comment by cyraid** [comment]
I'm not exactly sure where I would find out about the problem when it pops up saying "I made a backup go ahead" (for the api updater). Which scripts need updating? I've already updated the two spots for the Android JNI.

**Comment by StevenKek** [comment]
@legas1 Hi Daniel, greetings from czechia! Any idea as to when, approximately, is the pure java based plugin you mentioned going to "hit the shelves"?

**Comment by legas1** [comment]
@StevenKek hey there! Honestly... no idea. I haven't tried it yet, but there is already build located at https://github.com/playgameservices/play-games-plugin-for-unity/blob/android-java-client/current-build/GooglePlayGamesPlugin-0.10.01.unitypackage
