### ISSUE TITLE
play-games-plugin-for-unity and Tapjoy problem

### ISSUE THREAD

**Issue by Technoise** [playgameservices/play-games-plugin-for-unity#2735]
Hello ~!

I have some problem.

I import TapjoyUnityPlugin on Unity 2019.1.13f1 and it works well.

after than I import play-games-plugin-for unity-0.9.64 and finish setup.

gradle build is no problem but when I run it, the log show me 

E/TapjoyLog:TapjoyConnect: Type=INTEGRATION_ERROR;Message=Tapjoy SDK is disabled because Google Play Services was not found. For more information about including the Google Play services client library visit http://developer.android.com/google/play-services/setup.html or http://tech.tapjoy.com/product-overview/sdk-change-log/tapjoy-and-identifiers

do you have any idea for that issue ?
(tapjoy use google-play-services)

**Comment by ozdemir08** [comment]
Please check it out with the latest version of the plugin and let us know if the issue still persists.

**Comment by juliodutra2003** [comment]
Same problem here with the latests versions of both plugins:

Error TapjoyLog:TapjoyConnect Type=INTEGRATION_ERROR;Message=Tapjoy SDK is disabled because Google Play Services was not found. For more information about including the Google Play services client library visit http://developer.android.com/google/play-services/setup.html or http://tech.tapjoy.com/product-overview/sdk-change-log/tapjoy-and-identifiers
