### ISSUE TITLE
'GoogleMobileAdsSettings' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by Harlampey** [playgameservices/play-games-plugin-for-unity#2881]
Tried setup ads with Easy Mobile Pro, but get error :/

https://imgur.com/gallery/phnFfjh

**Comment by mukhinid** [comment]
Hi! I searched a bit and found that Easy Mobile plugin uses GPGS, but I think this error aren't related to GPGS plugin because the code you provided on screenshot doesn't belong to it.

In short if you have access to this part of source code you should go to GoogleMobileAds.Editor.GoogleMobileAdsSettings property and change its access modifier to 'public'. That's a common mistake of inexperienced C# developers to mix up access modifiers and get this error. I recommend to learn this topic ([MSDN](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers) for help).

But in fact, I presume you do something wrong because I suppose that code is auto-generated and so developers of Easy Mobile plugin had a reason to use this access modifiers. I think you should seek help on their resources.

**Comment by ozdemir08** [comment]
Thanks for the answer @mukhinid. Yes, it doesn't look to be related with GPGS. That's why I'm closing this bug now. Feel free to reopen it if you still think it's related.

**Comment by JailbreakMax** [comment]
Does anyone mind telling me what part do I change?

**Comment by adilumar95** [comment]
> Does anyone mind telling me what part do I change?

change "internal" to "public" in the script
