### ISSUE TITLE
SavedGameRequestStatus posts Request Internal error every time I try to access the saved data.

### ISSUE THREAD

**Issue by XigmaSuji** [playgameservices/play-games-plugin-for-unity#2894]
Every time I try to run this I get "Saved Game Request Internal error"  for SavedGameRequestStatus when the function calls OnSavedGameOpened method, Can anyone help me fix this, Also Yes I use the latest version of the plugin also yes I have the proper auth id and everything.

**Comment by AnjanaWijesinghe** [comment]
I have the same problem, just copy pasted the given example code and tried it with on changes, still it is not working. I have tried to troubleshoot the origin of the error, no luck yet.

**Comment by XigmaSuji** [comment]
Yea, Please let me know If it is fixed buddy. We will also get back to you IF it does on our end.

**Comment by AnjanaWijesinghe** [comment]
I tried implementing the cubic pilot project given in samples as it has save games implemented, I get the same internal error from it as well. A screenshot of the debug after pressing the save button one time done using a phone is given below (captured by android monitor).
![cubic pilot save internal error](https://user-images.githubusercontent.com/39512045/82724582-bc1a1280-9cf4-11ea-92a9-7b6cea1dec33.png)
After pressing the save button the second time, a different error occurs, with google sign in being null. 
![cubic pilot save google sign in null (second press)](https://user-images.githubusercontent.com/39512045/82724636-16b36e80-9cf5-11ea-8882-85a3399ea07a.png)

Can someone please help me fix this issue? What am I doing wrong here?

**Comment by wacky444** [comment]
I'am getting the same error, the error seems to be in the AndroidHelperFragment.cs file when trying to add the listener in the ShowSelectSnapshotUI function:

`                AndroidTaskUtils.AddOnSuccessListener<AndroidJavaObject>(
                    task,
                    result =>
                    {`

**Comment by AnjanaWijesinghe** [comment]
With updating to the new version 0.10.09 (I have been using 0.10.08), I was able to find out more on the error, but still I'm not able to solve this.
![paly games services saved game feature not anabled](https://user-images.githubusercontent.com/39512045/82784379-08448e80-9e7e-11ea-9307-df0e53901e2f.png)

It mentions that I've not enabled save games in the play console, which I've done (verified it multiple times to be sure) and it has been well over 24 hours since I activated it. I have also ensured that under the API console project that Play Game Services, Play Game Management and Drive API are active. _EnableSavedGames_ is called by the builder as well.

**Comment by XigmaSuji** [comment]
> With updating to the new version 0.10.09 (I have been using 0.10.08), I was able to find out more on the error, but still I'm not able to solve this.
> ![paly games services saved game feature not anabled](https://user-images.githubusercontent.com/39512045/82784379-08448e80-9e7e-11ea-9307-df0e53901e2f.png)
> 
> It mentions that I've not enabled save games in the play console, which I've done (verified it multiple times to be sure) and it has been well over 24 hours since I activated it. I have also ensured that under the API console project that Play Game Services, Play Game Management and Drive API are active. _EnableSavedGames_ is called by the builder as well.

Hey pal! Did you find a fix?

**Comment by olehkuznetsov** [comment]
Can you provide your project application id, or package name, please?

**Comment by XigmaSuji** [comment]
com.xigmagames.thebonfireFL

**Comment by AnjanaWijesinghe** [comment]
> > With updating to the new version 0.10.09 (I have been using 0.10.08), I was able to find out more on the error, but still I'm not able to solve this.
> > ![paly games services saved game feature not anabled](https://user-images.githubusercontent.com/39512045/82784379-08448e80-9e7e-11ea-9307-df0e53901e2f.png)
> > It mentions that I've not enabled save games in the play console, which I've done (verified it multiple times to be sure) and it has been well over 24 hours since I activated it. I have also ensured that under the API console project that Play Game Services, Play Game Management and Drive API are active. _EnableSavedGames_ is called by the builder as well.
> 
> Hey pal! Did you find a fix?

Yes. It started working properly by itself. It appears that the problem was not on my end but the saved games service took well over 24 hours to be enabled. 
If you are still facing issues, check if you have published the changes after enabling saved games (this is in the game services window, the publish button will appear on the top right of the tab where you turn on saved games).

**Comment by olehkuznetsov** [comment]
Also you can try to add yourself to testers list to check unpublished changes.
