### ISSUE TITLE
Auth error but SOMETIMES ??

### ISSUE THREAD

**Issue by barissmutluuu** [playgameservices/play-games-plugin-for-unity#3101]
Hi everyone, I used to 10.12 to handle the auth issues. I could sign in finally in my test device. I tried for other devices but some of them are failed by Authentication Canceled. In addition that, one of them could only signed in by button but not automatically. Is there anyone who face this problem. Have you any suggest ?

**Comment by ozdemir08** [comment]
Automatic sign-in may not happen due to various reasons. One example is if you have multiple accounts on the device and it is not obvious which one to use, then automatic sign-in may fail. `Authentication Canceled` could potentially signify a configuration issue. Make sure that  you don't see `NOT CORRECTLY CONFIGURED` in your logs. if you still have problems, reopen this bug providing a bug report. Thanks!
