### ISSUE TITLE
Get the played time of a cloud save and solve conflict manually

### ISSUE THREAD

**Issue by Glintlabs** [playgameservices/play-games-plugin-for-unity#402]
Hello, I have two questions:
- Is there any way to get the played time of a cloud save?
- On the legacy cloud save, there was  the OnStateConflict method to merge two saved games. On the new cloud save system is theres any way to do the same thing?

                                                                                                        Thanks

**Comment by claywilkinson** [comment]
The Unity plugin API for SavedGames can be found at https://github.com/playgameservices/play-games-plugin-for-unity#saving-game-state-to-the-cloud

To answer your questions,

Part of the metadata returned for a saved game is the played time. See reference: https://developers.google.com/games/services/common/concepts/savedgames#saved_game_metadata

And, yes, the possibility for conflicting saved games still exists, so the API is still there.  It is improved a little since the most common resolutions can be done automatically, make it a little easier to resolve based on time played or last updated time.

**Comment by Glintlabs** [comment]
Thanks!
