### ISSUE TITLE
Conflict are ignored on Saved Game in 0.9.12

### ISSUE THREAD

**Issue by threeplus** [playgameservices/play-games-plugin-for-unity#417]
I am using the legacy 'Cloud Save service', and i am going to switch to the new 'saved game'.
I found that all conflict on the save are ignored in my devices. it always use the data with the lastest committed update. OpenWithAutomaticConflictResolution and OpenWithManualConflictResolution are having the same result. I have tested submitting save data using 2 devices in the sample CubicPilot_4.6 and my own project.
In the callback of SnapshotManager.Open(...), it always return VALID, but none of VALID_WITH_CONFLICT.

Moreover, how to can i merge the data if conflict happen? I can choose the data in ConflictCallback, but how can i merge 2 data?

**Comment by tyrmullen** [comment]
Several Snapshots issues should have been fixed in version 0.9.20.  You still cannot truly "merge" yet until you have resolved all conflicts though (conflicts must be resolved by choosing one of the two conflicting snapshots).  Once you have done so (so you have an opened snapshot with no conflict), you can commit arbitrary data on top of the final snapshot, so you can "merge" at that time.

**Comment by claywilkinson** [comment]
Closing since it is obsolete - newer versions of play-services-games fixes this issue.
