### ISSUE TITLE
Push notification -> App Launch -> Register a Match Delegate

### ISSUE THREAD

**Issue by javalotte** [playgameservices/play-games-plugin-for-unity#431]
Clicking on a notification in a turn-based match takes the user to the play game services app.  Then subsequently clicking on the game in question will take the user to the app itself.  

However, if the app is not already running, this will result in the app being launched and calling Start() which will then register the Match Delegate callback, but at this point, its too late since the delegate has already been triggered?

Or am I wrong in that if auto-login is implemented, the match delegate will still function correctly on a fresh launch of the app?

Thanks.

**Comment by claywilkinson** [comment]
The delegate will be registered, and it is not invoked until the player is logged in.  So if the player never logs in, the delegate is not called.

If a different player is logged into the game when the notification is received in the Play Games App, then that user is automatically logged out and the new player is set so that silent login will work for the player that the invitation is intended for.
