### ISSUE TITLE
Using plugin on Android devices with version below 4.0

### ISSUE THREAD

**Issue by Karu1977** [playgameservices/play-games-plugin-for-unity#434]
Hello. Requirements for Andriod say:

To deploy on Android:
    Android SDK
    Android v4.0 or higher
    Google Play Services library, version 6.1.11 or above

It's sad, because Unity allows building for Andriod 2.3.1 and above, and some of players who running my game are using old Andriod versions. Is there some Google Service limitations for Android versions below 4.0?

What will happen if I run game with "play-games-plugin-for-unity" included on Android devices with versions below 4.0?

**Comment by claywilkinson** [comment]
There are substantial changes to the API (mostly new features added) since Gingerbread (version 2.3).  The biggest issue you may run into is that before version 4.0 a GPU (Graphical Processing Unit) and OpenGL support was optional.  

I don't have a specific answer of all the issues, I know the latest plugin will not work pre 4.0 and at this time we don't have plans to support pre 4.0 devices.  With that said though, please feel free to download the old code for the plugin and see what happens :)  \

Good Luck!

**Comment by Karu1977** [comment]
Thanks. However, is it safe to call methods on old devices? Will it cause crashes or just safely return false on trying to autenticate?

**Comment by claywilkinson** [comment]
Hmm. Good question :)  I think it depends on what is being called. The Unity player has settings that filter out devices (for example, you need to have armeabi-v7 processor (or x86), and opengl 2.0.  These filters are added to the AndroidManifest.xml, so I think a device that does not have these things cannot even install the app from the Play store.

Please share what you find out !

**Comment by claywilkinson** [comment]
Please reopen if you have more questions.
