### ISSUE TITLE
Real Time Multiplayer Realiable Message Send

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/play-games-plugin-for-unity#468]
I want to leave the current active room right after I send a reliable message to opponent and be sure he took the message properley. When I send message and leave the room immediately, meesage sometimes goes but sometimes not even it is reliable. How can I do that?

**Comment by anhnguyenvn** [comment]
hi @simsis3d 
1. If you want current player to inform his leaving before he calls leaveRoom(), i think it's not neccessary because other players have OnPeerDisconnected() listener.
2. If you still need to send a final message before leaving, I think after sending the final message, current player is still able to wait for something like "I_HAVE_RECEIVED_YOUR_FINAL" message from all of other players. Then he can call leaveRoom()

**Comment by Leuthil** [comment]
I think the misconception is that a reliable packet (not message) will always make it, which is not true. Sending a reliable message means that it will wait for an acknowledgement and if not it will send the message again, but if you leave right away you don't give a chance for Google Play Services to re-send again if need be.

**Comment by claywilkinson** [comment]
Yes, @Leuthil  are correct.  "Reliable message" should be read in the context of [TCP](https://en.wikipedia.org/wiki/Transmission_Control_Protocol).  This means it is a reliable transport.  In contrast, the unreliable message uses [UDP](https://en.wikipedia.org/wiki/User_Datagram_Protocol) which is connectionless.

The application level reliability is up to the developer, as @anhnguyenvn  suggested.

**Comment by claywilkinson** [comment]
OK to close this one?
