### ISSUE TITLE
Quests - Reward Data. How do I wright the file?

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#547]
Hi! 

Im trying to implement Quests to my game but I dont understand how I should write the Reward Data File thet I need to attach. They suggest Json but I have no idea what that is...(Yeah, Im a noob) Can I wright something in C#, and how would that look like? Lets say I want my global Int Points to increase with +10.

//Erik

**Comment by claywilkinson** [comment]
[JSON](http://en.wikipedia.org/wiki/JSON) is a method of serialization that is concise and easy for both humans and parsers to understand.  The data file for a quest can be in any format.  Once the quest is completed, the file contents are read by the app so any rewards can be applied.

JSON is nice since you can multiple fields very easily.  For example, if you wanted to increase the points by 10, the JSON would be
`{
"points" : 10
}`

If you are only awarding points, you could also simply put the point amount in the file as a string
`10` and then parse it to an int in your app.

If you want to explore JSON more in Unity, their wiki has a nice JSON implementation: http://wiki.unity3d.com/index.php/SimpleJSON

**Comment by Hoffa25** [comment]
Ok thanks!

So i should make a new cs file and just have the following lines:

using SimpleJSON;
{ "points" : 10 }

...and submit this file to the google console?

and in my game i must have a global int variable called "points"... and that should work?

**Comment by claywilkinson** [comment]
the file you submit should only have {"points" : 10}

**Comment by Hoffa25** [comment]
I have really tried to solve this on my own since you answered but it seems like its to much for me (i have only been programming for 6 months). In my main game script i have declared my variable "questpoints" that i want to increase when the player gets the reward.

"using SimpleJson;
...

public static int questpoints;"

But I dont understand what I need to wright to make the script fetch the incoming reward data and increase the questpoints. I have read the wiki you linked but didnt help me all the way:/

As the reward file I have only one line of c#:   {"questpoints" : 10}

//Erik

**Comment by claywilkinson** [comment]
OK to close this issue?

**Comment by Hoffa25** [comment]
Sure. I havnt got it to work but Im a noob and I will figure it out some day:)

**Comment by claywilkinson** [comment]
OK - thanks.  There is a sample, TrivalQuest for this, I'll add it to the list to make sure it shows a simple way to read the reward data.
