### ISSUE TITLE
Authentication always getting failed...

### ISSUE THREAD

**Issue by GanapathyGames** [playgameservices/play-games-plugin-for-unity#556]
void Start () {
		
		PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().EnableSavedGames().Build();
		PlayGamesPlatform.InitializeInstance(config);
		PlayGamesPlatform.DebugLogEnabled = true;
		PlayGamesPlatform.Activate();
		Social.localUser.Authenticate((bool success) => {if(success){Debug.Log("Succ");}
		});
	}

It always returns false i don't know where it goes wrong

**Comment by paradizIscool** [comment]
Hello,
I'm stucked at same point, don't know why, I certainly missed something.

I have this
gms.StatusHelper Status from wire: INVALID_CLIENT_ID status: null

but I've checked everything twice and all seems to be good (application id, bundle id, sha1 client id).

**Comment by claywilkinson** [comment]
Glad you figured it out :+1:

**Comment by paradizIscool** [comment]
don't close it, I've note created issue

**Comment by claywilkinson** [comment]
@paradizIscool  are you able to get authenticated or not?  From your edit it appeared that you have resolved the problem - so I closed the issue.  If you are still having  problems, can you post a log?

**Comment by Jablesp** [comment]
I am also having a very similar problem. Whenever I click the authenticate button, the green Google Play image pops up, if there is multiple accounts on the device it will ask to choose one to use, if the account does not have Google+ it will take me to set one up. But no matter what I do on what device I use, after all of that it goes back to showing the loading wheel, then the Minimal sample returns to looking exactly how it did before I started. No error messages or anything. This is all I get out of the debug log whenever I press authenticate:

Creating platform specific Play Games client
Creating real IPlayGamesClient
Entering state BeforeRoomCreateStartedState
Defaulting to no op
entering shutdown state
Defaulting to no op
Sign in error not authorized
Sign in error not authorized
Invoking user callback on game thread.

My version is in beta and I'm running it off of an account that is allowed to test. I have been browsing for days trying to find a solution to no avail. Launch is slowly approaching and I really don't want this to become a major setback.

Please help if you can, thanks in advance.

**Comment by claywilkinson** [comment]
@Jablesp  - Can you create a new issue (to keep your situation separate from this one) and post a log of when you are logging in and having problems?

**Comment by sorab2142** [comment]
@Jablesp 
1. Check the manifest for your correct APP_ID, 
2. Make sure the bundle identifier is the same as the one in the Linked Apps section of the Google Play Console
3. The email ID you are using to login to Play Services needs to be under Testing section in the Play Console.
4. Use the keystore file for which you submittted the SHA1 for (in the Console when linking the app) to sign the game (in Unity)

**Comment by ashkan-saeedi-mazdeh** [comment]
Check the manifest file to include your App ID, SHA1 of the signing certificate should match the one which you used for creating client ID and the user should be in testers group. If you sign with debug key then user explicitly should be there and being in beta/alpha groups doesn't help since you can not upload an apk signed with debug key.
Latest version of google play services should be downloaded and installed as well (I think it will ask for it in the UI if required).

After solving these all, I succeded  
Also if your account doesn't have an avatar image you'll encounter an exception when trying to load user image, There is a bug in LocalUser.cs in LoadImage which checks the URL value for not being null but not the empty string. I've fixed it and wil send it as a pull request with my other feature.
