### ISSUE TITLE
Getting email id of the user after authentication.

### ISSUE THREAD

**Issue by rakeshchatra** [playgameservices/play-games-plugin-for-unity#583]
Let say after the user clicks on the google sign in from the goggle play service. Once the authentication is completed successfully the information of the user we will be getting is Id, UserName, Isfriend, Underage etc using Social.localUser. Is there any way to get the userEmailId in unity directly after the authentication ??

**Comment by claywilkinson** [comment]
Currently getting the player's email is not part of the plugin.  There is a enhancement logged to add this feature.

**Comment by rakeshchatra** [comment]
will that be added sometime ??

**Comment by claywilkinson** [comment]
This has been added to the plugin.  In order to get the email address, you need to create a web application that is linked to the game.  This enables the additional permissions that are needed from the player in order to get the email address.

You can look at the SmokeTest sample app, which has a method call DoUserInfo which gets the email address of the currently logged in player.

**Comment by rakeshchatra** [comment]
Thank you for noticing that and adding this feature. Thanks a lot !

Rakesh Chatra T K
Software Developer 
www.juegostudio.com | rakesh.chatra@juegostudio.com
Ph:
  9538333447
