### ISSUE TITLE
Is there a stripped version?

### ISSUE THREAD

**Issue by LucRyan** [playgameservices/play-games-plugin-for-unity#610]
Hey there!

In my project, the method count is already really close to 65K. ( I tried my best to stripped out unnecessary classes, but some fat ass Ads SDK are required for some reason.)

Is there a way I can configure the plugin to not register classes that i don't want to use? 
e.g. `nearby`, `games/multiplayer`, `games/quest` etc.

I only want to use `Auth` and `Achievement`.

Now it gives me all these exceptions:
```
Part of the log:

E  Can't register class com/google/android/gms/games/quest/Quest: an exception occurred.
E  Can't register class com/google/android/gms/games/quest/QuestBuffer: an exception occurred.
E  Can't register class com/google/android/gms/games/quest/Quests: an exception occurred.
E  Can't register class com/google/android/gms/games/quest/Milestone: an exception occurred.
E  Can't register class com/google/android/gms/games/quest/Quests$LoadQuestsResult: an exception occurred.
E  Can't register class com/google/android/gms/games/quest/Quests$AcceptQuestResult: an exception occurred.
E  Can't register class com/google/android/gms/games/quest/Quests$ClaimMilestoneResult: an exception occurred.
E  Can't register class com/google/android/gms/games/snapshot/Snapshot: an exception occurred.
E  Can't register class com/google/android/gms/games/snapshot/SnapshotContents: an exception occurred.          
E  Can't register class com/google/android/gms/nearby/Nearby: an exception occurred.
E  Can't register class com/google/android/gms/nearby/connection/AppIdentifier: an exception occurred.
E  Can't register class com/google/android/gms/nearby/connection/AppMetadata: an exception occurred.
E  Can't register class com/google/android/gms/nearby/connection/Connections: an exception occurred.
E  Can't register class com/google/android/gms/nearby/connection/Connections$StartAdvertisingResult: an exception occurred.
```
Thanks!

Ryan

**Comment by Qbit86** [comment]
Any suggestions on how to reduce method references count would be very much appreciated! I've hit 65K limit and don't know what to do.

Thanks!

**Comment by mcraiha** [comment]
As LucRyan points out, it would be easier for developers if we could select what parts of the SDK we actually want to use.

 Qbit86: My current strip .bat script is following
```
REM First thing is to remove com and META-INF folders (play services extracts to these)
rd /S /Q com
rd /S /Q META-INF
REM Second thing is to extract the .jar file
"C:\Program Files\7-Zip\7z.exe" x google-play-services.jar
REM Then remove unneeded folders
rd /S /Q com\google\android\gms\appdatasearch
rd /S /Q com\google\android\gms\appindexing
rd /S /Q com\google\android\gms\cast
rd /S /Q com\google\android\gms\drive
rd /S /Q com\google\android\gms\fitness
rd /S /Q com\google\android\gms\location
rd /S /Q com\google\android\gms\maps
rd /S /Q com\google\android\gms\panorama
rd /S /Q com\google\android\gms\plus
rd /S /Q com\google\android\gms\search
rd /S /Q com\google\android\gms\wallet
rd /S /Q com\google\android\gms\wearable
REM package the slimmed down thingy
"c:\Program Files\Java\jdk1.8.0_31\bin\jar.exe" cf google-play-services_stripped.jar com/
```
You can replace 7z with other tool that supports .zip extracting. This script outputs google-play-services_stripped.jar that works with Unity plugin.

**Comment by Qbit86** [comment]
mcraiha: Thanks, I've tried, and this approach seems to work, though needs further testing.

Is it safe to strip `com\google\android\gms\nearby` out if we use Photon for networking, not Google services? The same about `wallet`: is it necessary for in-app billing?

In general: how to reveal dependencies to be sure, that stripping modules out does not breaks calls in runtime?

**Comment by mcraiha** [comment]
Qbit86: You can't strip nearby with latest play-games-plugin-for-unity since otherwise the plugin won't start (as LucRyan pointed out). Wallet isn't needed, and it hasn't any relations to IAB AFAIK.

I haven't seen any tool that can be used for dependencies checking. Big problem is that in Android environment code can generate more code during runtime and swap targets, so it would be kind of tricky to figure out all needed paths for all different devices.
e.g.
```
E/dalvikvm( 6466): Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zza
W/dalvikvm( 6466): VFY: unable to resolve check-cast 20 (Landroid/app/AppOpsManager;) in Lcom/google/android/gms/common/GooglePlayServicesUtil;
D/dalvikvm( 6466): VFY: replacing opcode 0x1f at 0x000e
```

**Comment by tyrmullen** [comment]
With the latest version of the Android SDK/Unity Plug-in, the appstate folder should also be no longer necessary, so that's one quick win.

Additionally, if you're not using anything Nearby-related, for example, it might be possible to compile your own com/google/android/gms/nearby/Nearby.class with no extra methods, and just replace it in the client jar.  The class itself needs to be found (as evidenced by the "can't register" error), but if none of the methods for a class are ever being used, they shouldn't need to be included.  I haven't tried this out for myself yet though.

Of course, these are all still just workarounds until a full solution is released, and while Nearby seems like a possible candidate for removal-if-unused, it's tougher to say with certainty that other classes are fine to "blank out" this way, so in general, I'd probably not do this unless absolutely necessary.  [Since, as mcraiha points out, a lot of the effort can occur at runtime, making full dependency checking a really gross problem].

**Comment by zentuit** [comment]
For the Mac/Linux users, I forked dextorer's google-play-services-strip-script script & config file which does a similar thing as @mcraiha 's batch file. I updated the strip.conf file to match the batch file also.

you can find it here: https://gist.github.com/zentuit/4bff5dc9a5086db39bef

**Comment by claywilkinson** [comment]
The plugin has been updated in version 0.9.27 to use the aar libraries vs. the client lib project.  This will result in much smaller apk file sizes and a substantial reduction in the number of dex entries.

**Comment by LucRyan** [comment]
wow thank you @claywilkinson !!

**Comment by zentuit** [comment]
That's awesome news @claywilkinson !
