### ISSUE TITLE
It's very unfortunate that GPGS never notifies G+ user about incoming invitation if user don't have that App/Game already installed.

### ISSUE THREAD

**Issue by chetanisinanand** [playgameservices/play-games-plugin-for-unity#625]
GPGS is deep linked  in App/Games , however unlike other popular plugins(Facebook etc) GPGS never notifies user about an invitation if user don't have that App/Game installed already 

If I invite someone in my circle who don't have that App/Game already installed. Google should atleast trigger a notification on Google+ or trigger an email stating someone invited you to play this game.

I believe this is the most important enhancement that is required for GPGS popularity and its usefulness.

I don't want to praise other SDK here, However just for example, when someone invite you on Facebook, A Facebook notification will be triggered. On clicking that notification it will redirect you to the App/Game ( if already installed on that device) or to the AppStore ( if not already installed) from where user can download it.

Google Team, please look into this.

Also, I would request everyone who is reading this post to comment below and boost this post, so that Google take it forward, because this feature will exponentially drive your App/Games INSTALLS using powerful Google+ social network.

**Comment by claywilkinson** [comment]
Thanks for the feedback! What you describe sounds like a nice feature. I'll pass it along

**Comment by Hoffa25** [comment]
I agree! 

Im asking for a similar thing in this thread: https://github.com/playgameservices/play-games-plugin-for-unity/issues/573#issuecomment-111837944 . Clawilkinson links to this:  https://developers.google.com/app-invites/    ...but im kind of a noob so I dont understand if that solution really do what I want (or what you are asking for here) . Seems more to be a way to invite firends to install your app rather than to install AND at the same time have a game-inivitation waiting when you log in to the game the first time. ..but again Im not sure..

**Comment by claywilkinson** [comment]
Just a minor re-iteration of the original comment.  The functionality we are talking about here (getting a link to install a game *and* an a multiplayer invitation is supported currently.  The requirement is to have the Google Play Games app installed.  This comes standard on all devices that run Google Play Services, and for the most part updates automatically.  Users can of course control this, but it seem pretty rare.  If your experience is different, I'd love to hear about it. (I still passed this along as an enhancement in order to cover the edge cases).

**Comment by Hoffa25** [comment]
Ok so if I send an invitation via the current gpg unity plugin (the create match with invitation function) and the user dont have the app installed (but have the google play games app installed), they will get notified via the gpg app?

...well i tried that now but it didnt work:/ ..perhaps because the device that sshould have recieved the invite runs on android 4.4..?

**Comment by Hoffa25** [comment]
..or perhaps its because the game is still in beta mode?

**Comment by claywilkinson** [comment]
The Android version should not be an issue.  The beta mode is definitely suspect.  Is the person invited listed as a tester?

**Comment by Hoffa25** [comment]
Yes hes invited as a tester. ...and game invites, turn based matches, etc. works just fine when the tester has installed the app.

**Comment by Hoffa25** [comment]
It seems like its the android version causing the problem! When I uninstall my game completely on 5.0 device and send an invitation from 4.4 it works fine! The invitation comes up with a download link in the gpg app! Its when I try the opposite: to send invite from 5.0 to 4.4 nothing happens on the 4.4 device.

**Comment by claywilkinson** [comment]
I believe this has been finally corrected in the play services libraries.  Please re-open another issue if the invitation is not being received correctly.
