### ISSUE TITLE
Authenticate fail at first time,success at second time

### ISSUE THREAD

**Issue by yayaigo2010** [playgameservices/play-games-plugin-for-unity#655]
I click my button,I can see my google name at the top of the ui view,login success,
Authenticate callback return false at first time,
then click my button again,it just return true,but why?
This is my code below:

    void buttonEvent()
    {

     Social.localUser.Authenticate((bool success) => {         
        if(success)
             ....
        else
           show fail message dialog
      });
    }

**Comment by claywilkinson** [comment]
Can you provide a log of this happening?  It will help understand what is going on.

**Comment by yayaigo2010** [comment]
I run on android device, what log do you mean?

**Comment by claywilkinson** [comment]
Thanks - that helps.

**Comment by VladimirKuznetsov** [comment]
I got the same problem.

**Comment by claywilkinson** [comment]
Short answer, this is expected behavior.  It is possible to have the callback for Authenticate to be called multiple times.  The underlying library attempts a silent login when starting authentication for the first time.  If this fails, the callback is called.  Then, the call to authenticate that is coded in the plugin is called, this  one probably is not a silent login, and it succeeds.

**Comment by claywilkinson** [comment]
Version 0.9.25 cleans up an extra callback.

**Comment by balpreets10** [comment]
This issue still comes in 0.9.64
Using 0.9.53 to get a successful login
