### ISSUE TITLE
OnPeerDisconnected doesnt get called if other player disconnects from internet

### ISSUE THREAD

**Issue by sorab2142** [playgameservices/play-games-plugin-for-unity#680]
Is there a long time out till it happens? Because for me it didn't trigger the function at all.
The case is when the other player turns of their internet or loses their connection momentarily, ideally I would expect it to disconnect them from the room but it seems the connection is kept alive for a while. 

If it is indeed kept alive, how would I go about syncing up their states? Since the game data would have been missing for the time he had dropped out.

**Comment by claywilkinson** [comment]
Intermittent connection loss on a mobile device is an extremely common event, so the game services try to tolerate this.  What I would suggest is that you design the game communication so that each message contains the state of the game, or that there is a way to incrementally rebuild the shared state.  One way to do this is to have a serial number on the game state, and when a player sends a message, send the game state serial number, and what the app thinks is the latest game state serial number.  If there is a mismatch when receiving, send a message asking for a "sync-up" message to get back in sync.

The other alternative is when you detect the serial number is behind, is to disconnect the player.

I'm interested in hearing what you end up doing!

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
