### ISSUE TITLE
GTMOAuth2Authentication.h not found

### ISSUE THREAD

**Issue by sorab2142** [playgameservices/play-games-plugin-for-unity#694]
XCode says it cant find the file GTMOAuth2Authentication.h
Compiling with 0.9.25 and Unity 5.1.3.f1 IL2CPP for armv7
This is my podfile:

    platform :ios, '7.0'

    target 'Unity-iPhone' do
    pod 'GooglePlayGames', '~> 5.0'
    pod 'Google-Mobile-Ads-SDK', '~> 7.0'
    end

    target 'Unity-iPhone Tests' do
    pod 'GooglePlayGames', '~> 5.0'
    end

I ran "pod install" after adding the GoogleMobileAds line and have "Enable Modules" set to true in Build Settings. 

What am I missing in the setup?

**Comment by sorab2142** [comment]
Tried with Unity 5.1.3p3 and still stuck on the same error.

**Comment by claywilkinson** [comment]
The latest version of GooglePlayGames does not use Google Plus sign in any longer. (This is the sdk that provides GTMOAuth2Authentication).  Are you trying to use this class directly, or just use something to get authenticated for the game services?  If it is the latter, the plugin generates the correct code in GPGSAppController.  If you have CustomWebViewApplication.mm still, you can remove this file.  The functionality in that file has been merged into the GPGSController.

**Comment by sorab2142** [comment]
If it isnt dependant on it then why is the file getting generated?
I am also using Ultimate Mobile Plugin from Stans Assets... could it be because of his GPG plugin conflicting with it?

I deleted CustomWebViewApplication.mm and then got an error in GPGSAppController stating GooglePlus.h was not found, and if I remove that line, it will now show a bunch of errors for GPPUrl, etc.

**Comment by claywilkinson** [comment]
You might want to delete the Plugins directory (or at least the parts coming from Google's plugin) and the GooglePlayGames directory and re-import the package.  0.9.25 does not contain the CustomWebViewApplication.mm file, so it should not be there.  Then run Window>GooglePlayGames>Setup>iOS Setup...

Then re-generate the xcode project.

**Comment by ZenithCode** [comment]
I changed imports to this to make it work:

#import <GoogleSignIn/GIDSignIn.h>
#import <GoogleSignIn/GIDGoogleUser.h>
#import <GoogleSignIn/GIDAuthentication.h>
#import <GoogleSignIn/GIDProfileData.h>

Right?

**Comment by claywilkinson** [comment]
I use those plus ios_support.h and GPGEnums.h
```
#import <GIDSignIn.h>
#import <GIDGoogleUser.h>
#import <GIDAuthentication.h>
#import <GIDProfileData.h>
#import <gpg/ios_support.h>
#import <gpg/GPGEnums.h>
```

**Comment by ZenithCode** [comment]
Do you import the GoogleSignIn framework in a different way than this?

If I don't modify the path to say #import < GoogleSignIn/GIDSignIn.h> returns class not found.

<img width="247" alt="screen shot 2015-09-15 at 22 43 37" src="https://cloud.githubusercontent.com/assets/1938034/9889541/45ece298-5bfb-11e5-8415-cdef5e7ac5b8.png">

**Comment by claywilkinson** [comment]
I use cocoapods - I don't add the framework path to the import - since the framework include is added to the include searchpath, it is not needed.
I just did a clean build and it was OK:

![screen shot 2015-09-15 at 1 51 49 pm](https://cloud.githubusercontent.com/assets/8752378/9889773/f9f8617c-5bb0-11e5-8574-0fa386e3dd6a.png)

**Comment by ZenithCode** [comment]
I will try and start using cocoapods then.

(Suggestion) - Can you update the setup documentation in that Unity window (right after a build) with instructions on how to use cocoapods?  Right now, they still explain the manual process of adding frameworks etc.

Thanks.

**Comment by claywilkinson** [comment]
Thanks for the suggestion! -- I'll try to make it more clear

**Comment by tyrmullen** [comment]
Cocoapods is definitely the easiest way to resolve dependencies for iOS.

A few quick tips to add to what was said above: instead of importing all the GID* .h files, you're covered by just importing the umbrella header GoogleSignIn.h.  Also, if you *do* decide to add frameworks and bundles manually instead of using CocoaPods (again, not recommended), then you will want to remove GooglePlus bundle and framework from before and replace them with GoogleSignIn bundle and framework.  The GoogleOpenSource framework will also need to be kept-- that's the framework specifically which contains GTMOAuth2Authentication.h, for the record.
