### ISSUE TITLE
Cannot see input box for IOS client ID

### ISSUE THREAD

**Issue by sorab2142** [playgameservices/play-games-plugin-for-unity#695]
![screen shot 2015-09-15 at 3 21 15 pm](https://cloud.githubusercontent.com/assets/3336237/9873480/b48dbbfc-5bbd-11e5-8cd8-ae77fecddf4e.png)
As you can see there are two boxes for WebClientID (optional) but the first one is actually for the IOS Client ID (visible by the description) but there isnt any input area for the IOS client ID.

Shouldn't there be an input box for it?

**Comment by ZenithCode** [comment]
You have to copy resource from Google dashboard and paste it in resources definition box.  The client ID is part of that resource data.

**Comment by sorab2142** [comment]
@ZenithCode the box for inputting iosClient ID isnt even visible!

**Comment by sorab2142** [comment]
Okay

**Comment by claywilkinson** [comment]
This is correct - The thought behind the change was 2-fold.  First, it reduces the number copy & pastes needed - especially if you have a lot of events or achievements.  Second, it makes it easy to detect when the iOS app is not linked and authorized since it will not appear in the resource data.

Always looking for ways to make it better - please share any ideas!
