### ISSUE TITLE
Not Uploading .p12 file to Google Play Developer Console

### ISSUE THREAD

**Issue by kunal01** [playgameservices/play-games-plugin-for-unity#702]
Hello
I create .p12 certificate for development & when i upload to Developer Console,it says Certificate Upload Failed.

So what can i do?

**Comment by ZenithCode** [comment]
This was happening to me too - most probably its a bug in the console. I created a new game to resolve the issue.

**Comment by kunal01** [comment]
if i create new ios game then i have to setup play service in unity again because OAuth2 Client ID is changed.Is that right?

**Comment by kunal01** [comment]
@ZenithCode still not uploading...

**Comment by claywilkinson** [comment]
@kunal01 Is the console giving an error message?

Things to check:
1. The p12 must have a password
2. The p12 must only have 1 certificate in it.
3. The bundle ID must match the one in the certificate
4. Make sure the prod and dev certificates are associated with the correct  field.

You can check the certificates by running:
` openssl pkcs12 -info -in mycert.p12`
Enter the password and it display information.  The subject should look something like:
**subject=/UID=com.google.games.unitytbmp/CN=Apple Development IOS Push Services: com.google.games.unitytbmp/OU=EQHXZ8M8AV/C=US**

Where in this case *com.google.games.unitytbmp* is the bundle Id.  This is a development certificate since the CN equals *Apple Development IOS Push Services"  it will be Apple Production.... for prod.

**Comment by Jessicardo** [comment]
For anyone still having this issue, the solution for me was to not select both the key and the certificate for export - rather just export the certificate which ALREADY includes the key.
