### ISSUE TITLE
[iOS] Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by yafarida** [playgameservices/play-games-plugin-for-unity#728]
Hi! I'm trying to build my project on iOS using Unity 4.6.7, latest plugin version (25) and xcode 7 + iOS SDK 9. Got the following error. The same problem when building only for arm7. I'm following plugin's manual and there is no more compiling errors. Thanks!

Undefined symbols for architecture arm64:
  "__GooglePlayGetUserEmail", referenced from:
      _IOSTokenClient__GooglePlayGetUserEmail_m722 in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _IOSTokenClient__GooglePlayGetUserEmail_m722_MethodInfo, _IOSTokenClient__GooglePlayGetUserEmail_m722 )
  "__GooglePlayGetAccessToken", referenced from:
      _IOSTokenClient__GooglePlayGetAccessToken_m721 in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _IOSTokenClient__GooglePlayGetAccessToken_m721, _IOSTokenClient__GooglePlayGetAccessToken_m721_MethodInfo )
  "__GooglePlayGetIdToken", referenced from:
      _IOSTokenClient__GooglePlayGetIdToken_m720 in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _IOSTokenClient__GooglePlayGetIdToken_m720_MethodInfo, _IOSTokenClient__GooglePlayGetIdToken_m720 )
  "__GooglePlayEnableProfileScope", referenced from:
      _IOSClient__GooglePlayEnableProfileScope_m716 in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _IOSClient__GooglePlayEnableProfileScope_m716_MethodInfo, _IOSClient__GooglePlayEnableProfileScope_m716 )
ld: symbol(s) not found for architecture arm64

**Comment by Armend** [comment]
I had this bug too. I followed the steps at https://developers.google.com/games/services/ios/quickstart "Option 2: Manual installation" because CocoaPods doesn't seems to work for me. Well, at least it creates the "Unity-iPhone.xcworkspace" automatically.
For me i had to add an additional Framwork: StoreKit.framework. This was not listed in "Option 2" but was necessary for me. 

After doing this steps there might be an other Error, something like "Cannot find GoogleSignIn.h" that's because the path is not right. You have to edit the imports from "#import <GoogleSignIn.h>" to "#import <GoogleSignIn/GoogleSignIn.h>". This must be done for the other "Cannot find xxx"-Errors too.(I think there where 3-5 of them) 

I hope this is the solution for you too.  Remember that CocoaPods did create the "Unity-iPhone.xcworkspace" automatically after building on Unity. So you should have installed CocoaPods.

**Comment by yafarida** [comment]
@Armend Thanks, but I have GoogleSignIn and StoreKit added. I'm not using CocoaPods. I have also fixed #import directives. So I'm gonna try it with Cocoa(

**Comment by yafarida** [comment]
Project build was successful with CocoaPods but I have to disable Bitcode. So I guess there is something missed in build instructions. At least:
- StoreKit is required
- #import directive must be fixed
- Bitcode should be disabled

**Comment by claywilkinson** [comment]
The updated plugin, 0.9.30 uses the update 5.1 version of the Google Play Games SDK for C++.  This should address all these issues.
