### ISSUE TITLE
undefined symbols for architecture _OBJC_CLASS_$_SFSafariViewController

### ISSUE THREAD

**Issue by phathh93** [playgameservices/play-games-plugin-for-unity#736]
Hi! i'm trying to build my project on Xcode 6.4.
when linking i got the following error

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_SFSafariViewController", referenced from:
      objc-class-ref in libSignIn.a(GIDSignIn.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

im doing all following plugin's manual. Searching like crazy my hole day for that.
 Anyone help me!

**Comment by banditdevelopment** [comment]
Sometimes I get that error in Xcode 6.4.

Try upgrading to Xcode 7. Once I upgraded the error went away.

**Comment by claywilkinson** [comment]
This is because GoogleSignin version 2.3.0 is expecting iOS 9 (which added the SafariViewController).

Upgrading definitely fixes the issue, you can also change your project to use version 2.2  of GoogleSignIn by adding the line
`pod 'GoogleSignIn', '2.2.0' `
to your Podfile, and re-running `pod update`

**Comment by claywilkinson** [comment]
@phathh93  - OK to close this one?  The simplest solution is to update Xcode.

**Comment by phathh93** [comment]
sorry for long reply @claywilkinson , i busy with another proj so i forgot to check this. Thank for your help @claywilkinson , my error is long gone :).

**Comment by ElizaSapir** [comment]
add SafariServices framework!
