### ISSUE TITLE
ERROR_NOT_AUTHORIZED

### ISSUE THREAD

**Issue by Renato-Malachite** [playgameservices/play-games-plugin-for-unity#775]
Hello guys, Im having an issue on authentication as well.

I triple checked and my email is on tester but Im getting the following error:

[Play Games Plugin DLL] 10/25/15 21:38:17 -02:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

I 'published' the game services some hours ago, maybe it takes some time to get up an running?

**Comment by Renato-Malachite** [comment]
Nobody?

I just created an empty project with just one button and the codes for authentication and keep getting the same error.....

**Comment by sorab2142** [comment]
1. Check bundle ID (aka package name) matching the one in the Console.
2. Check the keystore being used to sign the application, it has to be the one which you linked the android app in the console.
3. If that doesn't work download the latest version of the plugin, and run Setup Android again, maybe the generated manifest doesn't have the right bundle id (if you change it in step 1). 

You don't need to publish game services to get log-in to work.

**Comment by malachitebr** [comment]
I found out what was happening....

I knew it wasnt a problem with the plugin, but, asked for help because maybe someone was having the same issue.

Long story short, I had googleplay games console properly configured, tester accounts properly configured, BUT on googplay console (note, not google play GAMES console) I had 'accidentaly' marked the app for deletion and this was causing the problem.

So, in order for this integration work we should ALWAYS check the following:
1- Bundle ID must match with everything (googleplay console, googleplaygame console and etc..)
2- The application should be linked inside game services
3- Make sure you use the same SHA1 for the entire process, all your api configuration should use the same credentials based on the same SHA1 that was used for signing your app.

If you dont mess with the configs like I did, probably everything will work as intended, but if you are as stupid as me (haha) and are having trouble, always check the above list.

**Comment by claywilkinson** [comment]
Thanks for sharing what happened!  Glad you got it working.

**Comment by malachitebr** [comment]
It took many hours to figure out this simple solution, but, it is important for us to have such intel because others might get in the same situation.

**Comment by claywilkinson** [comment]
Yes, I agree - the configuration is painfully tricky.  Thanks again.

**Comment by ducvn** [comment]
I just meet issue, i realize that APIs required for basic Games Services to work. So please enable these service. Hope this will solve your problem.
