### ISSUE TITLE
Gifting

### ISSUE THREAD

**Issue by paolo-lionhg** [playgameservices/play-games-plugin-for-unity#786]
I'm just curious if this will ever be implemented in this plugin and any idea when. Thank you. And also thank you for the continuous updates. This plugin really helped me a lot. I wish I could also contribute.

**Comment by claywilkinson** [comment]
Gifting is on the list, but no specific timeframe.  When i know more, I'll update this thread.  Glad that this plugin is helpful!  In terms of contributing, this is an open source project, so feel free to contribute code, or documentation improvements.  At the very least, please share your experience and ideas (such as gifting support) with the community.

**Comment by banditdevelopment** [comment]
+1 for gifting! Currently, there is no good way to gift in-app purchases on either Android or iOS. 

The best method currently seems to be a generated code that a user can input into the game to unlock whatever the IAP would have. Obviously the drawback is that if the user re-installs the game, any unlocked items would not be re-unlocked by a refreshment of the IAPs.

Hope this gives you some ideas of what you could implement for gifting @paolo-lionhg.

**Comment by claywilkinson** [comment]
I got some feedback from the people working on the Gifting API for Games.  There is currently no support for Gifting on iOS, and adoption of Gifting on Android has been relatively low.  As a result, it is on the internal "todo" list, but not a priority in the short term.

I am going to close this issue, feel free to comment, etc on it.  And we'll revisit Gifting when there is a more solid plan.

**Comment by banditdevelopment** [comment]
@claywilkinson By "adoption of Gifting on Android has been relatively low" do you mean there is some system already in place?

By the way, I don't think this is a GPGS specific feature, but a general Play Store feature request that should not be in Unity GPGS Github. :)

**Comment by claywilkinson** [comment]
Hmmm - maybe we are talking about different things?  There is an in-game gift API for android: https://developers.google.com/games/services/android/giftRequests  which is what I thought you were referring to. (So low it is almost secret :)? ).

**Comment by banditdevelopment** [comment]
I'm talking about a different type of gifting; I want to gift non-consumable in-app purchases to my users. I don't think this is currently possible.

**Comment by claywilkinson** [comment]
Ahh - agreed - I don't think there is an easy way to do this.  I'll make sure I pass along the clarification.

**Comment by paolo-lionhg** [comment]
for me i was talking about the consumable gifting. right now i am using a generated code and my server database to make my own gifting system. the biggest problem here is when the user needs to input the code. with gpgs there is no need for user input in gifting. plus it would show consistency in my game.
 thanks for the feedback.

**Comment by ilmarioranen** [comment]
"I'm talking about a different type of gifting; I want to gift non-consumable in-app purchases to my users. I don't think this is currently possible."

This is also what intend to do, more or less, but I dont see why the Google Play game gifts feature couldn't be used for it (at least the difficult part). I mean its up to you to decide what happens when a gift is accepted. It could unlock something that is normally available only via IAP. Google wont track the gift after its consumed, but you could still save the gift in game in a hidden cloud-based variable, which makes the gift permanent across devices etc.

And AFAIK the gift sender could either buy gifts (to be sent to others), or get them for free or whatever reason. The feature could be even used to (kinda) gift a whole app to a friend or family member (if the app is free but content is available via IAP). I can see that VERY usefull for example for parents wanting to gift the game/content to their kids, who dont have a credit card attached on their accounts. 

Also, I've talked to a Google employee who told that game gifts is a very underused but potentially great booster for both revenue and viral expansion of user base. So I believe implementing game gift support could be a hugely important feature for developers who know what to do with it.
