### ISSUE TITLE
Google Play Game Service and AdMob ads

### ISSUE THREAD

**Issue by shlapkoff** [playgameservices/play-games-plugin-for-unity#801]
I use the 0.9.27 version of the plugin.
After the addition of plugin, it removes the directory Assets/Plugins/Android/google-play-services_lib which is necessary for the plugin AdMob. AdMob plugin is not working.

Actions:
1. Create empty unity project;
2. Import Appodeal unity3d sdk: 
https://s3-us-west-1.amazonaws.com/appodeal-crossplatform/appodeal-unity/1.13.7_0.5.4/Appodeal.unitypackage
3. Import Google play game service plugin

**Comment by phamdanh** [comment]
I got same problem too

**Comment by tonghae** [comment]
Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-games:8.1+
  at Google.JarResolver.PlayServicesSupport.LoadDependencies (Boolean allClients) [0x00000] in <filename unknown>:0 
  at Google.JarResolver.PlayServicesSupport.CreateInstance (System.String clientName, System.String sdkPath, System.String settingsDirectory) [0x00000] in <filename unknown>:0 
  at GooglePlayGames.BackgroundResolution..cctor () [0x00000] in /Users/anubis/Projects/World of Toilets/Assets/GooglePlayGames/Editor/BackgroundResolution.cs:40 
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

I think my problem is similar. It removes Assets/Plugins/Android/google-play-services_lib if I try to put it back.

**Comment by OracleParadiser** [comment]
The same.

Removing Assets/Plugins/Android/google-play-services_lib because the asset does not exist
UnityEditor.AssetDatabase:Refresh()
GooglePlayGames.GPGSUpgrader:.cctor() (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:91)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

**Comment by tonghae** [comment]
Yeah, same error —
No resource found that matches the given name (at 'theme' with value '@style/Theme.IAPTheme')

**Comment by claywilkinson** [comment]
OK - so the plugin is clearly "too smart" for its own good.  Short answer - in Assets/GooglePlayGames/Editor/GPGSUpgrader.cs delete lines [81-82](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Editor/GPGSUpgrader.cs#L81).  This will stop the repeated deleting of google-play-services-lib.  Then add back the directory, then delete the Assets/Plugins/Android/*.aar files - since these duplicate the classes in the entire google-play-services-lib.

This change was made to the games plugin because the google-play-services-lib increases the apk size by 50% since it includes the entire Google SDK, including things like wear, auto, and other APIs that have nothing to do with games.

You can try to do the same for the admob plugin by doing the following:
1. Don't comment out  GPGSUpgrader as described above.
2. Edit Assets/GooglePlayGames/Editor/BackroundResolution.cs
2.1 Add the following line at line 67:
``            svcSupport.DependOn("com.google.android.gms",
                "play-services-ads",
                PluginVersion.PlayServicesVersionConstraint);
``

This should copy over the ads library.

I have not tried it explicitly, but this should work since it is modeled after how to build an app using AdMob using Android Studio.  Please let me know if you try it out!

**Comment by tonghae** [comment]
After updating BackgroundResolution.cs, getting this error:

Error: [Temp/StagingArea/AndroidManifest-main.xml, /Users/anubis/Projects/World of Toilets/Temp/StagingArea/android-libraries/play-services-ads-8.3.0/AndroidManifest.xml:10] Trying to merge incompatible /manifest/application/activity[@name=com.google.android.gms.ads.AdActivity]

stderr[
Error: [Temp/StagingArea/AndroidManifest-main.xml, /Users/anubis/Projects/World of Toilets/Temp/StagingArea/android-libraries/play-services-ads-8.3.0/AndroidManifest.xml:10] Trying to merge incompatible /manifest/application/activity[@name=com.google.android.gms.ads.AdActivity] element:
  <activity
--    @android:name="com.google.android.gms.ads.AdActivity">
--</activity>
--(end reached)
  <activity
++    @android:name="com.google.android.gms.ads.AdActivity"
++    @android:theme="@android:style/Theme.Translucent">
++</activity>
]

**Comment by tonghae** [comment]
Thanks! It helped me. Project compiled successfully and the ads are showing normally.
Besides editing BackgroundResolution.cs I commented following line in Plugins/Android/GoogleMobileAdsPlugin/AndroidManifest.xml to make project compile:

<activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"/>

**Comment by OracleParadiser** [comment]
No. It doesn't help...
Commenting 81-82 lines prevents deleting. But project isn't compiling. Cannot merge manifest related to aar file. (cannot merge Activity)...
I cannot delete aar files. They are recovering. I deselected them in inspector. After this project compiled but goggle servises was absent in game...

**Comment by bumblebee77** [comment]
same problem here.

**Comment by plelos** [comment]
I did the same of tonghae and it worked!

**Comment by claywilkinson** [comment]
Also check #814 - which documents the success of using these two together.

**Comment by PhannGor** [comment]
...\android-sdk\extras\google\m2repository\com\google\android\gms\play-services-ads\8.4.0

**Comment by PhannGor** [comment]
I would prefer do not touch GPGS package. Just don't import `google-play-services_lib` and `android-support-v4.jar` from the Appodeal SDK package. Instead copy `play-services-ads-8.4.0.aar` from
`android-sdk/extras/google/m2repository/com/google/android/gms/play-services-ads/8.4.0` to `/Plugins/Android`.

Also use `/Plugins/Android/MainLibProj/AndroidManifest.xml` instead of `/Plugins/Android/AndroidManifest.xml` to add permissions, activities and metadata required for Appodeal SDK.

This approach works for me at least for Unity 5.3.1 and Appodeal SDK 1.13.10.

**Comment by claywilkinson** [comment]
The admob plugin has been updated to 3.0.0 and now is compatible with the Play Game Services plugin.
https://github.com/googleads/googleads-mobile-unity
