### ISSUE TITLE
Can I use OnRealTimeMessageReceived method multiple time

### ISSUE THREAD

**Issue by gamozome** [playgameservices/play-games-plugin-for-unity#826]
OnRealTimeMessageReceived method Can be used in multiple scripts.. ?

In my case i have two scripts , both having send and receive method.
but only one script send and receives data.
another script does not seems to be working.

**Comment by claywilkinson** [comment]
The OnRealTimeMessageReceived method is part of the RealTimeMultiplayerListener interface.  The object implementing this interface is passed in when creating the room instance or accepting an invitation.  Since this is done only once per game, I am not sure how you are using two?  Can you explain/show how you are registering both listeners?

The best solution is to have 1 object implement OnRealTimeMessageReceived, and then have it dispatch messages to other scripts.

**Comment by gamozome** [comment]
Thank you,
I have pass received message to other scripts. and it work..
