### ISSUE TITLE
0.9.27 automatically deleting folder (google-play-services_lib)

### ISSUE THREAD

**Issue by paolo-lionhg** [playgameservices/play-games-plugin-for-unity#832]
i don't know what's happening, but 0.9.27 is automatically deleting folder google-play-services_lib. i need that folder for google ads (https://github.com/googleads/googleads-mobile-unity). without it i am getting an error: AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize.

**Comment by claywilkinson** [comment]
You'll have packaging problems including both.  We're working on updating the ads plugin to work in a similar way.   See issue  #814  for discussion on how to work around it.

The  advantage of the aar file approach is that only the required resources and methods are pulled in making for a leaner application, and it is annoyingly automated :)

In the immediate term, you have two options:

1. add the following lines to Assets/GooglePlayGames/Editor/BackgroundResolution.cs around line 70:
```
            // Ads
            svcSupport.DependOn("com.google.android.gms",
                "play-services-ads",
                PluginVersion.PlayServicesVersionConstraint);
```
and then edit Plugin/Android/GoogleMobileAdsPlugin/AndroidManifest.xml and remove:
```
<activity android:name="com.google.android.gms.ads.AdActivity" ... />
<activity android:name="com.google.android.gms.ads.purchase.InAppPurchaseActivity".../>
```

Or option 2:
delete BackgroundResolution.cs, and the aar files in the plugin/Android directory and add back google-play-services_lib.

**Comment by paolo-lionhg** [comment]
nice. thanks. i had to revert my project back to using 0.9.26 in order for me to continue working. but maybe tomorrow i will try out your solution.

**Comment by cult2ash** [comment]
i'm using google analytics plugin(https://github.com/googleanalytics/google-analytics-plugin-for-unity).
delete BackgroundResolution.cs, and all aar files in the plugin/Android directory, but still automatically deleting that folder.

**Comment by cult2ash** [comment]
Self answer......
i found Assets/GooglePlayGames/Editor/GPGUpgrade.cs line 81.
```
string clientDir = "Assets/Plugins/Android/google-play-services_lib";
GPGSUtil.DeleteDirIfExists(clientDir);
```
delete it and worked well.

**Comment by claywilkinson** [comment]
Oh! great -- thanks for sharing the answer!  I'll make a note to move that so it does not get run all the time...

**Comment by OracleParadiser** [comment]
It's enough to delete only activity (at least in my case)
<activity android:name="com.google.android.gms.ads.AdActivity" ... />

**Comment by paolo-lionhg** [comment]
option 1 works. but i think i am having problems with the ad plugin. ads are no longer showing. i even tried a fresh project with just the ads plugin but it still does not work. anyway its not related with this one.

1 bug down, another one came up. lol

**Comment by natysoz** [comment]
Heyzap , 1/2/2016 still 0.9.3 Remove the google-play-services_lib Folder, What to do i must get the Admob too to work on my game!

**Comment by Disar** [comment]
Naty it's deleted by class GPGSUpgrader. I don't know if it's wise to delete those things.

Im facing the same issue where I can't build due to the fact Neatplugs admob stuff is probably referring to a different version or something. Im kinda lost.

**Comment by claywilkinson** [comment]
Here's some more insight into the situation, hopefully clear up some of the confusion :)

The google-play-services_lib contains the entire client library for all of Google Play Services.  This covers everything from games, to wear, to auto. It is a huge footprint since there are so many features.  Any one application only needs a part of this library, so most of it just taking up space in the APK, and filling up the DEX limit (which is 64k methods).  Many game developers are sensitive to download size and as the number of plugins for analytics, in-app purchases, and game services grow, there is more pressure on hitting the DEX limit. 

To improve this situation, we switched to using the .aar libraries to import just the parts of the Play Services library that are needed.  For most simple games this resulted in a huge reduction in size and freed up a lot of DEX space.

The .aar files are in $ANDROID_HOME/sdk/extras/google/m2repository (in a maven repository format).  This is a much more efficient way to import the client library.

The [jar resolver library](https://github.com/googlesamples/unity-jar-resolver) used to copy over the .aar files into the project is open sourced as a model of how plugins can make it easy to keep the client library up to date and minimize conflicts with other plugins while keeping the resulting application lean.

**Comment by natysoz** [comment]
ok i got this 1 its help me but strange , no errors on build , on empty scene the heyzap demo work 

on my scene , its not. but this is what this guys are missing : 

	
I am using Google Play Games 0.9.30 and Google mobile ads plugin 2.2.1. They both working fine together.

First import GPG plugin and run a setup. Then import Admob plugin and copy play-services-ads-8.4.0.aar from android sdk

sdk/extras/google/m2repository/com/google/android/gms/play-services-ads/8.4.0/play-services-ads-8.4.0.aar
to Assets/Plugins/Android folder.

Next open Android manifest from Assets/Plugins/Android/GoogleMobileAdsPlugin/AndroidManifest and comment the following lines

<meta-data android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />
<activity android:name="com.google.android.gms.ads.AdActivity"
   android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"/>
Now i am able to successfully test Interstitial Ads and GPGS.

**Comment by natysoz** [comment]
i got it work , talk with me on skype i will explain how to combine them bro , Natysoz2
