### ISSUE TITLE
When add the Game Gifts to "Play Games plugin fro Unity"?

### ISSUE THREAD

**Issue by DziD** [playgameservices/play-games-plugin-for-unity#924]
Hello!

I'm a little bit confused, in plugin for unity (by GOOGLE !!!!) Games Gifts is not presented, but Google created it!

Add it, it gives players more fun

https://developers.google.com/games/services/android/giftRequests

**Comment by claywilkinson** [comment]
I've passed along the request.  Can you describe how you would use it?  This would help motivate the decision process,

**Comment by DziD** [comment]
Hello!

In order to players exchanged game money and unique game items. Besides if this game isn't installed when opening the notice, the application will be installed and the player will receive a gift. It is possible to present to the friend passing to a certain level (it is very cool thing)

**Comment by claywilkinson** [comment]
Thanks for the description.  I'll pass it along to strengthen the enhancement request.  In the mean time, you can always use JNI to access the Java SDK directly.

**Comment by DziD** [comment]
use gifts through JNI very problematically :))) I already tried

**Comment by smennesson** [comment]
Hello,

we're also using gifts in our project and we would be happy to see it implemented in the official plugin. 

We did implement gifts in September 2014 above the 0.9.02 version of the official plugin, we could share the code if necessary but I suppose the plugin has too much evolved since our implementation.

For the moment, we will have to deactivate gifts in our project because we need to use the latest version of the official plugin, in order to support new permissions of Android 6. So it would greatly help us if gifts could be added officially.

Our needs are:
* being able to send a gift request
* being able to handle requests programmatically (list opened requests and accept a request)

Thanks

**Comment by claywilkinson** [comment]
Thanks for the comments @smennesson.

**Comment by smennesson** [comment]
@claywilkinson Hi Clay, any idea if this will be done and if so when? Our game is Tekken Card Tournament, you can find it here on the Play Store : https://play.google.com/store/apps/details?id=eu.namcobandaigames.tekkencard, it has more than 10M downloads.

The Gift feature can be seen by clicking on the Stamina bar in the header, this is the "Ask stamina to your circles" button.

**Comment by SirMorland** [comment]
Hi!

Any updates on this yet? I'm currently developing a "trading card game" styled game where I would like the players to trade their cards with each other using Google gifts.

**Comment by claywilkinson** [comment]
Unfortunately, Gifts are being deprecated. https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
