### ISSUE TITLE
Connecting to more than a single opponent when minimum opponents = 1 and maximum opponents = 3

### ISSUE THREAD

**Issue by TamimSha** [playgameservices/play-games-plugin-for-unity#926]
I'm having trouble connecting more than 2 players into a room when matchmaking.
It seams that the second player that clicked will always connect to the first player and start the game; completely ignoring the third player even though the third player click only a few milliseconds after the second.
Is there anyway around this other than changing the minimum number of opponents to 2 or more?

**Comment by danspeedy1** [comment]
You make each of the players "friends" on Google Plus and then use/implement the Invite Friends functionality so setup a game.

I don't believe you can test more than two players using the Quick Game functionality without a large amount of devices. The reason is, you have the minimum number of players set to 2 and as soon as GPS sees two players ready to play it will connect them for a game. If you had many players (I'm guessing around 10 or more) then you may have a chance of Google queuing up the players and then assigning them to a game with more than 2 players.

**Comment by WangLee** [comment]
Thanks for the advice!

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
