### ISSUE TITLE
Permission changes affect on plugin / token retrieval?

### ISSUE THREAD

**Issue by rkachowski** [playgameservices/play-games-plugin-for-unity#928]
It would be great to know how the announced permissions changes ( http://android-developers.blogspot.de/2016/01/play-games-permissions-are-changing-in.html?m=1 ) affect the plugin development.

Specifically, are the [access token / id token](https://github.com/playgameservices/play-games-plugin-for-unity#retrieving-players-email-or-access-token) api's still the recommended method of getting this information? The article mentions passing an auth code to the server, and getting the **access token** from there, rather than passing the token directly. 

Does the same issue apply for the **id token** ?

**Comment by claywilkinson** [comment]
Yes, things are changing.  The access token and id token that are exposed in this plugin are for Google Plus. The 'GetServerAuthCode' will be in the next version of the plugin (hopefully this week).  This code should be passed to the server, where it can be exchanged for the token.  The G+ APIs will stay around for a while, but you should plan to stop using them in the near future in order to take advantage of a more frictionless player experience.

**Comment by AminSojoudi** [comment]
Please make a callback for this API so that we can find out when AuthCode is recieved.

**Comment by claywilkinson** [comment]
The updated plugin version 0.9.30 contains these updates.  Including the callback pattern for GetServerAuthCode().

**Comment by AminSojoudi** [comment]
Thanks
